"""Apply MCMC posterior writeback to the three .mod files.

Reads `mcmc_writeback.txt` (generated by extract_mcmc_results.m), parses
out parameter and shock-std lines, and updates the matching lines in
au_pac.mod, au_pac_var.mod, au_pac_mce.mod with the new posterior
means. Preserves the rest of each .mod file untouched.

Run after run_bayesian_mcmc.m + extract_mcmc_results.m.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WRITEBACK = ROOT / "mcmc_writeback.txt"
MODS = [ROOT / "au_pac.mod",
        ROOT / "au_pac_var.mod",
        ROOT / "au_pac_mce.mod"]


def parse_writeback():
    """Yield (name, value, comment) for parameters and shocks."""
    text = WRITEBACK.read_text()
    # Parameter lines look like:
    #   b0_pQ           =  0.0226;    // posterior mean, 90% HPD [...]
    pat_param = re.compile(
        r"^\s*([a-zA-Z_]\w*)\s*=\s*([\-\+0-9eE\.]+);\s*//\s*(.*)$",
        re.M,
    )
    for m in pat_param.finditer(text):
        yield ("param", m.group(1), float(m.group(2)), m.group(3))

    # Shock lines look like:
    #   var eps_q;        stderr 0.4771;    // posterior mean, 90% HPD [...]
    pat_shock = re.compile(
        r"^\s*var\s+([a-zA-Z_]\w*);\s+stderr\s+([\-\+0-9eE\.]+);\s*//\s*(.*)$",
        re.M,
    )
    for m in pat_shock.finditer(text):
        yield ("shock", m.group(1), float(m.group(2)), m.group(3))


def update_param_line(text, name, value, comment_suffix):
    """Replace `name = OLDVAL;` with `name = NEWVAL;` preserving comment."""
    pat = re.compile(
        rf"^(\s*{re.escape(name)}\s*=\s*)([\-\+0-9eE\.]+)(\s*;\s*)(//.*)?$",
        re.M,
    )
    n_subs = [0]

    def _sub(m):
        n_subs[0] += 1
        new_comment = m.group(4) or ""
        # Append "(MCMC YYYY-MM-DD)" if not already there
        suffix = f"// MCMC refresh 2026-05-11: {comment_suffix}"
        if "MCMC refresh 2026-05-11" not in new_comment:
            new_comment = suffix
        return f"{m.group(1)}{value:.4f}{m.group(3)}{new_comment}"

    new_text = pat.sub(_sub, text)
    return new_text, n_subs[0]


def update_shock_line(text, eps_name, value, comment_suffix):
    """Replace `var eps_X; stderr OLDVAL;` with new stderr value."""
    pat = re.compile(
        rf"^(\s*var\s+{re.escape(eps_name)};\s+stderr\s+)([\-\+0-9eE\.]+)(\s*;\s*)(//.*)?$",
        re.M,
    )
    n_subs = [0]

    def _sub(m):
        n_subs[0] += 1
        new_comment = m.group(4) or ""
        suffix = f"// MCMC refresh 2026-05-11: {comment_suffix}"
        if "MCMC refresh 2026-05-11" not in new_comment:
            new_comment = suffix
        return f"{m.group(1)}{value:.4f}{m.group(3)}{new_comment}"

    new_text = pat.sub(_sub, text)
    return new_text, n_subs[0]


def main():
    if not WRITEBACK.exists():
        raise SystemExit(f"Missing {WRITEBACK} — run extract_mcmc_results.m first")

    entries = list(parse_writeback())
    print(f"Parsed {len(entries)} updates from {WRITEBACK.name}")
    if not entries:
        raise SystemExit("No parameter or shock lines parsed — check writeback format")

    for mod_path in MODS:
        if not mod_path.exists():
            print(f"  skip {mod_path.name} (missing)")
            continue
        text = mod_path.read_text()
        total = 0
        for kind, name, value, comment in entries:
            if kind == "param":
                text, n = update_param_line(text, name, value, comment)
            else:
                text, n = update_shock_line(text, name, value, comment)
            total += n
        mod_path.write_text(text)
        print(f"  {mod_path.name}: {total} substitutions applied")

    print("Done.")


if __name__ == "__main__":
    main()
