function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(6)=params(15);
    ys_(7)=params(16);
    ys_(8)=params(17);
    ys_(1)=0;
    ys_(4)=0;
    ys_(2)=params(15);
    ys_(3)=params(16);
    ys_(5)=params(17);
    ys_(9)=0;
    ys_(10)=0;
    ys_(11)=0;
    % Auxiliary equations
end
