%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'aux_pQ';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(14,1);
M_.exo_names_tex = cell(14,1);
M_.exo_names_long = cell(14,1);
M_.exo_names(1) = {'eps_q'};
M_.exo_names_tex(1) = {'eps\_q'};
M_.exo_names_long(1) = {'eps_q'};
M_.exo_names(2) = {'eps_i'};
M_.exo_names_tex(2) = {'eps\_i'};
M_.exo_names_long(2) = {'eps_i'};
M_.exo_names(3) = {'eps_pi'};
M_.exo_names_tex(3) = {'eps\_pi'};
M_.exo_names_long(3) = {'eps_pi'};
M_.exo_names(4) = {'eps_q_us'};
M_.exo_names_tex(4) = {'eps\_q\_us'};
M_.exo_names_long(4) = {'eps_q_us'};
M_.exo_names(5) = {'eps_pi_us'};
M_.exo_names_tex(5) = {'eps\_pi\_us'};
M_.exo_names_long(5) = {'eps_pi_us'};
M_.exo_names(6) = {'eps_ibar'};
M_.exo_names_tex(6) = {'eps\_ibar'};
M_.exo_names_long(6) = {'eps_ibar'};
M_.exo_names(7) = {'eps_pibar_au'};
M_.exo_names_tex(7) = {'eps\_pibar\_au'};
M_.exo_names_long(7) = {'eps_pibar_au'};
M_.exo_names(8) = {'eps_pibar_us'};
M_.exo_names_tex(8) = {'eps\_pibar\_us'};
M_.exo_names_long(8) = {'eps_pibar_us'};
M_.exo_names(9) = {'eps_u_gap'};
M_.exo_names_tex(9) = {'eps\_u\_gap'};
M_.exo_names_long(9) = {'eps_u_gap'};
M_.exo_names(10) = {'eps_piQ'};
M_.exo_names_tex(10) = {'eps\_piQ'};
M_.exo_names_long(10) = {'eps_piQ'};
M_.exo_names(11) = {'eps_pi_m'};
M_.exo_names_tex(11) = {'eps\_pi\_m'};
M_.exo_names_long(11) = {'eps_pi_m'};
M_.exo_names(12) = {'eps_pcom'};
M_.exo_names_tex(12) = {'eps\_pcom'};
M_.exo_names_long(12) = {'eps_pcom'};
M_.exo_names(13) = {'eps_var_pQ'};
M_.exo_names_tex(13) = {'eps\_var\_pQ'};
M_.exo_names_long(13) = {'eps_var_pQ'};
M_.exo_names(14) = {'eps_pQ'};
M_.exo_names_tex(14) = {'eps\_pQ'};
M_.exo_names_long(14) = {'eps_pQ'};
M_.endo_names = cell(17,1);
M_.endo_names_tex = cell(17,1);
M_.endo_names_long = cell(17,1);
M_.endo_names(1) = {'yhat_au'};
M_.endo_names_tex(1) = {'yhat\_au'};
M_.endo_names_long(1) = {'yhat_au'};
M_.endo_names(2) = {'pi_au_gap'};
M_.endo_names_tex(2) = {'pi\_au\_gap'};
M_.endo_names_long(2) = {'pi_au_gap'};
M_.endo_names(3) = {'i_gap'};
M_.endo_names_tex(3) = {'i\_gap'};
M_.endo_names_long(3) = {'i_gap'};
M_.endo_names(4) = {'u_gap'};
M_.endo_names_tex(4) = {'u\_gap'};
M_.endo_names_long(4) = {'u_gap'};
M_.endo_names(5) = {'yhat_us'};
M_.endo_names_tex(5) = {'yhat\_us'};
M_.endo_names_long(5) = {'yhat_us'};
M_.endo_names(6) = {'pi_us_gap'};
M_.endo_names_tex(6) = {'pi\_us\_gap'};
M_.endo_names_long(6) = {'pi_us_gap'};
M_.endo_names(7) = {'ibar'};
M_.endo_names_tex(7) = {'ibar'};
M_.endo_names_long(7) = {'ibar'};
M_.endo_names(8) = {'pibar_au'};
M_.endo_names_tex(8) = {'pibar\_au'};
M_.endo_names_long(8) = {'pibar_au'};
M_.endo_names(9) = {'pibar_us'};
M_.endo_names_tex(9) = {'pibar\_us'};
M_.endo_names_long(9) = {'pibar_us'};
M_.endo_names(10) = {'piQ'};
M_.endo_names_tex(10) = {'piQ'};
M_.endo_names_long(10) = {'piQ'};
M_.endo_names(11) = {'pi_m'};
M_.endo_names_tex(11) = {'pi\_m'};
M_.endo_names_long(11) = {'pi_m'};
M_.endo_names(12) = {'dln_pcom'};
M_.endo_names_tex(12) = {'dln\_pcom'};
M_.endo_names_long(12) = {'dln_pcom'};
M_.endo_names(13) = {'piQ_hat'};
M_.endo_names_tex(13) = {'piQ\_hat'};
M_.endo_names_long(13) = {'piQ_hat'};
M_.endo_names(14) = {'pQ_level'};
M_.endo_names_tex(14) = {'pQ\_level'};
M_.endo_names_long(14) = {'pQ_level'};
M_.endo_names(15) = {'AUX_DIFF_165'};
M_.endo_names_tex(15) = {'AUX\_DIFF\_165'};
M_.endo_names_long(15) = {'AUX_DIFF_165'};
M_.endo_names(16) = {'AUX_DIFF_LAG_168'};
M_.endo_names_tex(16) = {'AUX\_DIFF\_LAG\_168'};
M_.endo_names_long(16) = {'AUX_DIFF_LAG_168'};
M_.endo_names(17) = {'pac_expectation_pac_pQ'};
M_.endo_names_tex(17) = {'pac\_expectation\_pac\_pQ'};
M_.endo_names_long(17) = {'pac_expectation_pac_pQ'};
M_.endo_partitions = struct();
M_.param_names = cell(48,1);
M_.param_names_tex = cell(48,1);
M_.param_names_long = cell(48,1);
M_.param_names(1) = {'delta'};
M_.param_names_tex(1) = {'delta'};
M_.param_names_long(1) = {'delta'};
M_.param_names(2) = {'lambda_q'};
M_.param_names_tex(2) = {'lambda\_q'};
M_.param_names_long(2) = {'lambda_q'};
M_.param_names(3) = {'sigma_q'};
M_.param_names_tex(3) = {'sigma\_q'};
M_.param_names_long(3) = {'sigma_q'};
M_.param_names(4) = {'lambda_i'};
M_.param_names_tex(4) = {'lambda\_i'};
M_.param_names_long(4) = {'lambda_i'};
M_.param_names(5) = {'alpha_i'};
M_.param_names_tex(5) = {'alpha\_i'};
M_.param_names_long(5) = {'alpha_i'};
M_.param_names(6) = {'beta_i'};
M_.param_names_tex(6) = {'beta\_i'};
M_.param_names_long(6) = {'beta_i'};
M_.param_names(7) = {'lambda_pi'};
M_.param_names_tex(7) = {'lambda\_pi'};
M_.param_names_long(7) = {'lambda_pi'};
M_.param_names(8) = {'kappa_pi'};
M_.param_names_tex(8) = {'kappa\_pi'};
M_.param_names_long(8) = {'kappa_pi'};
M_.param_names(9) = {'lambda_q_us'};
M_.param_names_tex(9) = {'lambda\_q\_us'};
M_.param_names_long(9) = {'lambda_q_us'};
M_.param_names(10) = {'lambda_pi_us'};
M_.param_names_tex(10) = {'lambda\_pi\_us'};
M_.param_names_long(10) = {'lambda_pi_us'};
M_.param_names(11) = {'kappa_pi_us'};
M_.param_names_tex(11) = {'kappa\_pi\_us'};
M_.param_names_long(11) = {'kappa_pi_us'};
M_.param_names(12) = {'lambda_ibar'};
M_.param_names_tex(12) = {'lambda\_ibar'};
M_.param_names_long(12) = {'lambda_ibar'};
M_.param_names(13) = {'lambda_pibar'};
M_.param_names_tex(13) = {'lambda\_pibar'};
M_.param_names_long(13) = {'lambda_pibar'};
M_.param_names(14) = {'lambda_pibar_us'};
M_.param_names_tex(14) = {'lambda\_pibar\_us'};
M_.param_names_long(14) = {'lambda_pibar_us'};
M_.param_names(15) = {'rho_u_gap'};
M_.param_names_tex(15) = {'rho\_u\_gap'};
M_.param_names_long(15) = {'rho_u_gap'};
M_.param_names(16) = {'okun_coeff'};
M_.param_names_tex(16) = {'okun\_coeff'};
M_.param_names_long(16) = {'okun_coeff'};
M_.param_names(17) = {'alpha_pc'};
M_.param_names_tex(17) = {'alpha\_pc'};
M_.param_names_long(17) = {'alpha_pc'};
M_.param_names(18) = {'beta_pc_m'};
M_.param_names_tex(18) = {'beta\_pc\_m'};
M_.param_names_long(18) = {'beta_pc_m'};
M_.param_names(19) = {'gamma_oil'};
M_.param_names_tex(19) = {'gamma\_oil'};
M_.param_names_long(19) = {'gamma_oil'};
M_.param_names(20) = {'i_ss'};
M_.param_names_tex(20) = {'i\_ss'};
M_.param_names_long(20) = {'i_ss'};
M_.param_names(21) = {'pi_ss_au'};
M_.param_names_tex(21) = {'pi\_ss\_au'};
M_.param_names_long(21) = {'pi_ss_au'};
M_.param_names(22) = {'pi_ss_us'};
M_.param_names_tex(22) = {'pi\_ss\_us'};
M_.param_names_long(22) = {'pi_ss_us'};
M_.param_names(23) = {'rho_pQ_aux'};
M_.param_names_tex(23) = {'rho\_pQ\_aux'};
M_.param_names_long(23) = {'rho_pQ_aux'};
M_.param_names(24) = {'a_pQ_y'};
M_.param_names_tex(24) = {'a\_pQ\_y'};
M_.param_names_long(24) = {'a_pQ_y'};
M_.param_names(25) = {'a_pQ_i'};
M_.param_names_tex(25) = {'a\_pQ\_i'};
M_.param_names_long(25) = {'a_pQ_i'};
M_.param_names(26) = {'a_pQ_pi'};
M_.param_names_tex(26) = {'a\_pQ\_pi'};
M_.param_names_long(26) = {'a_pQ_pi'};
M_.param_names(27) = {'a_pQ_u'};
M_.param_names_tex(27) = {'a\_pQ\_u'};
M_.param_names_long(27) = {'a_pQ_u'};
M_.param_names(28) = {'rho_piQ'};
M_.param_names_tex(28) = {'rho\_piQ'};
M_.param_names_long(28) = {'rho_piQ'};
M_.param_names(29) = {'rho_pi_m'};
M_.param_names_tex(29) = {'rho\_pi\_m'};
M_.param_names_long(29) = {'rho_pi_m'};
M_.param_names(30) = {'rho_pcom'};
M_.param_names_tex(30) = {'rho\_pcom'};
M_.param_names_long(30) = {'rho_pcom'};
M_.param_names(31) = {'b0_pQ'};
M_.param_names_tex(31) = {'b0\_pQ'};
M_.param_names_long(31) = {'b0_pQ'};
M_.param_names(32) = {'b1_pQ'};
M_.param_names_tex(32) = {'b1\_pQ'};
M_.param_names_long(32) = {'b1_pQ'};
M_.param_names(33) = {'b2_pQ'};
M_.param_names_tex(33) = {'b2\_pQ'};
M_.param_names_long(33) = {'b2_pQ'};
M_.param_names(34) = {'beta_pac'};
M_.param_names_tex(34) = {'beta\_pac'};
M_.param_names_long(34) = {'beta_pac'};
M_.param_names(35) = {'h_pac_pQ_constant'};
M_.param_names_tex(35) = {'h\_pac\_pQ\_constant'};
M_.param_names_long(35) = {'h_pac_pQ_constant'};
M_.param_names(36) = {'h_pac_pQ_var_yhat_au_lag_1'};
M_.param_names_tex(36) = {'h\_pac\_pQ\_var\_yhat\_au\_lag\_1'};
M_.param_names_long(36) = {'h_pac_pQ_var_yhat_au_lag_1'};
M_.param_names(37) = {'h_pac_pQ_var_i_gap_lag_1'};
M_.param_names_tex(37) = {'h\_pac\_pQ\_var\_i\_gap\_lag\_1'};
M_.param_names_long(37) = {'h_pac_pQ_var_i_gap_lag_1'};
M_.param_names(38) = {'h_pac_pQ_var_pi_au_gap_lag_1'};
M_.param_names_tex(38) = {'h\_pac\_pQ\_var\_pi\_au\_gap\_lag\_1'};
M_.param_names_long(38) = {'h_pac_pQ_var_pi_au_gap_lag_1'};
M_.param_names(39) = {'h_pac_pQ_var_u_gap_lag_1'};
M_.param_names_tex(39) = {'h\_pac\_pQ\_var\_u\_gap\_lag\_1'};
M_.param_names_long(39) = {'h_pac_pQ_var_u_gap_lag_1'};
M_.param_names(40) = {'h_pac_pQ_var_yhat_us_lag_1'};
M_.param_names_tex(40) = {'h\_pac\_pQ\_var\_yhat\_us\_lag\_1'};
M_.param_names_long(40) = {'h_pac_pQ_var_yhat_us_lag_1'};
M_.param_names(41) = {'h_pac_pQ_var_pi_us_gap_lag_1'};
M_.param_names_tex(41) = {'h\_pac\_pQ\_var\_pi\_us\_gap\_lag\_1'};
M_.param_names_long(41) = {'h_pac_pQ_var_pi_us_gap_lag_1'};
M_.param_names(42) = {'h_pac_pQ_var_ibar_lag_1'};
M_.param_names_tex(42) = {'h\_pac\_pQ\_var\_ibar\_lag\_1'};
M_.param_names_long(42) = {'h_pac_pQ_var_ibar_lag_1'};
M_.param_names(43) = {'h_pac_pQ_var_pibar_au_lag_1'};
M_.param_names_tex(43) = {'h\_pac\_pQ\_var\_pibar\_au\_lag\_1'};
M_.param_names_long(43) = {'h_pac_pQ_var_pibar_au_lag_1'};
M_.param_names(44) = {'h_pac_pQ_var_pibar_us_lag_1'};
M_.param_names_tex(44) = {'h\_pac\_pQ\_var\_pibar\_us\_lag\_1'};
M_.param_names_long(44) = {'h_pac_pQ_var_pibar_us_lag_1'};
M_.param_names(45) = {'h_pac_pQ_var_piQ_lag_1'};
M_.param_names_tex(45) = {'h\_pac\_pQ\_var\_piQ\_lag\_1'};
M_.param_names_long(45) = {'h_pac_pQ_var_piQ_lag_1'};
M_.param_names(46) = {'h_pac_pQ_var_pi_m_lag_1'};
M_.param_names_tex(46) = {'h\_pac\_pQ\_var\_pi\_m\_lag\_1'};
M_.param_names_long(46) = {'h_pac_pQ_var_pi_m_lag_1'};
M_.param_names(47) = {'h_pac_pQ_var_dln_pcom_lag_1'};
M_.param_names_tex(47) = {'h\_pac\_pQ\_var\_dln\_pcom\_lag\_1'};
M_.param_names_long(47) = {'h_pac_pQ_var_dln_pcom_lag_1'};
M_.param_names(48) = {'h_pac_pQ_var_piQ_hat_lag_1'};
M_.param_names_tex(48) = {'h\_pac\_pQ\_var\_piQ\_hat\_lag\_1'};
M_.param_names_long(48) = {'h_pac_pQ_var_piQ_hat_lag_1'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 14;
M_.endo_nbr = 17;
M_.param_nbr = 48;
M_.orig_endo_nbr = 14;
M_.aux_vars(1).endo_index = 15;
M_.aux_vars(1).type = 8;
M_.aux_vars(1).orig_index = 14;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'diff(pQ_level)';
M_.aux_vars(2).endo_index = 16;
M_.aux_vars(2).type = 9;
M_.aux_vars(2).orig_index = 15;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'diff(pQ_level(-1))';
M_.aux_vars(3).endo_index = 17;
M_.aux_vars(3).type = 12;
M_.aux_vars(3).orig_expr = 'h_pac_pQ_constant+yhat_au(-1)*h_pac_pQ_var_yhat_au_lag_1+i_gap(-1)*h_pac_pQ_var_i_gap_lag_1+pi_au_gap(-1)*h_pac_pQ_var_pi_au_gap_lag_1+u_gap(-1)*h_pac_pQ_var_u_gap_lag_1+yhat_us(-1)*h_pac_pQ_var_yhat_us_lag_1+pi_us_gap(-1)*h_pac_pQ_var_pi_us_gap_lag_1+ibar(-1)*h_pac_pQ_var_ibar_lag_1+pibar_au(-1)*h_pac_pQ_var_pibar_au_lag_1+pibar_us(-1)*h_pac_pQ_var_pibar_us_lag_1+piQ(-1)*h_pac_pQ_var_piQ_lag_1+pi_m(-1)*h_pac_pQ_var_pi_m_lag_1+dln_pcom(-1)*h_pac_pQ_var_dln_pcom_lag_1+piQ_hat(-1)*h_pac_pQ_var_piQ_hat_lag_1';
M_.var.esat_pQ.model_name = 'esat_pQ';
M_.var.esat_pQ.structural = false;
M_.var.esat_pQ.eqtags = {'var_yhat_au'; 'var_i_gap'; 'var_pi_au_gap'; 'var_u_gap'; 'var_yhat_us'; 'var_pi_us_gap'; 'var_ibar'; 'var_pibar_au'; 'var_pibar_us'; 'var_piQ'; 'var_pi_m'; 'var_dln_pcom'; 'var_piQ_hat'; };
M_.var.esat_pQ.eqn = [1 2 3 4 5 6 7 8 9 10 11 12 13 ];
M_.var.esat_pQ.lhs = [1 3 2 4 5 6 7 8 9 10 11 12 13 ];
M_.var.esat_pQ.max_lag = [1 1 1 1 1 1 1 1 1 1 1 1 1 ];
M_.var.esat_pQ.diff = [false false false false false false false false false false false false false ];
M_.var.esat_pQ.nonstationary = M_.var.esat_pQ.diff;
M_.var.esat_pQ.orig_diff_var = [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ];
M_.var.esat_pQ.rhs.vars_at_eq{1}.var = [1 2 3 5 ];
M_.var.esat_pQ.rhs.vars_at_eq{1}.lag = [-1 -1 -1 -1 ];
M_.var.esat_pQ.rhs.vars_at_eq{2}.var = [1 2 3 ];
M_.var.esat_pQ.rhs.vars_at_eq{2}.lag = [-1 -1 -1 ];
M_.var.esat_pQ.rhs.vars_at_eq{3}.var = [1 2 8 10 11 12 ];
M_.var.esat_pQ.rhs.vars_at_eq{3}.lag = [-1 -1 -1 -1 -1 -1 ];
M_.var.esat_pQ.rhs.vars_at_eq{4}.var = [1 4 ];
M_.var.esat_pQ.rhs.vars_at_eq{4}.lag = [-1 -1 ];
M_.var.esat_pQ.rhs.vars_at_eq{5}.var = [5 ];
M_.var.esat_pQ.rhs.vars_at_eq{5}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{6}.var = [5 6 ];
M_.var.esat_pQ.rhs.vars_at_eq{6}.lag = [-1 -1 ];
M_.var.esat_pQ.rhs.vars_at_eq{7}.var = [7 ];
M_.var.esat_pQ.rhs.vars_at_eq{7}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{8}.var = [8 ];
M_.var.esat_pQ.rhs.vars_at_eq{8}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{9}.var = [9 ];
M_.var.esat_pQ.rhs.vars_at_eq{9}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{10}.var = [10 ];
M_.var.esat_pQ.rhs.vars_at_eq{10}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{11}.var = [11 ];
M_.var.esat_pQ.rhs.vars_at_eq{11}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{12}.var = [12 ];
M_.var.esat_pQ.rhs.vars_at_eq{12}.lag = [-1 ];
M_.var.esat_pQ.rhs.vars_at_eq{13}.var = [1 2 3 4 13 ];
M_.var.esat_pQ.rhs.vars_at_eq{13}.lag = [-1 -1 -1 -1 -1 ];
M_.pac.pac_pQ.auxiliary_model_name = 'esat_pQ';
M_.pac.pac_pQ.discount_index = 34;
M_.pac.pac_pQ.h_param_indices = [35 36 37 38 39 40 41 42 43 44 45 46 47 48 ];
M_.pac.pac_pQ.aux_id = 17;
M_.pac.pac_pQ.eq_name = 'eq_piQ_pac';
M_.pac.pac_pQ.auxiliary_model_type = 'var';
M_.pac.pac_pQ.kind = '';
M_.pac.pac_pQ.lhs_var = 15;
M_.pac.pac_pQ.ec.params = 31;
M_.pac.pac_pQ.ec.vars = [13 14 ];
M_.pac.pac_pQ.ec.istarget = [true false ];
M_.pac.pac_pQ.ec.scale = [1 -1 ];
M_.pac.pac_pQ.ec.isendo = [true true ];
M_.pac.pac_pQ.ar.params = [32 ];
M_.pac.pac_pQ.ar.vars = [16 ];
M_.pac.pac_pQ.ar.lags = [0 ];
M_.pac.pac_pQ.max_lag = 1;
M_.pac.pac_pQ.additive.params = [NaN 33 ];
M_.pac.pac_pQ.additive.vars = [14 1 ];
M_.pac.pac_pQ.additive.isendo = [false true ];
M_.pac.pac_pQ.additive.lags = [0 0 ];
M_.pac.pac_pQ.additive.scaling_factor = [1 1 ];
M_.Sigma_e = zeros(14, 14);
M_.Correlation_matrix = eye(14, 14);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 17;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 0;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 0;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 1 16;
 2 17;
 3 18;
 4 19;
 5 20;
 6 21;
 7 22;
 8 23;
 9 24;
 10 25;
 11 26;
 12 27;
 13 28;
 14 29;
 15 30;
 0 31;
 0 32;]';
M_.nstatic = 2;
M_.nfwrd   = 0;
M_.npred   = 15;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 15;
M_.ndynamic   = 15;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'var_yhat_au' ;
  2 , 'name' , 'var_i_gap' ;
  3 , 'name' , 'var_pi_au_gap' ;
  4 , 'name' , 'var_u_gap' ;
  5 , 'name' , 'var_yhat_us' ;
  6 , 'name' , 'var_pi_us_gap' ;
  7 , 'name' , 'var_ibar' ;
  8 , 'name' , 'var_pibar_au' ;
  9 , 'name' , 'var_pibar_us' ;
  10 , 'name' , 'var_piQ' ;
  11 , 'name' , 'var_pi_m' ;
  12 , 'name' , 'var_dln_pcom' ;
  13 , 'name' , 'var_piQ_hat' ;
  14 , 'name' , 'eq_piQ_pac' ;
};
M_.mapping.yhat_au.eqidx = [1 2 3 4 13 14 17 ];
M_.mapping.pi_au_gap.eqidx = [1 2 3 13 17 ];
M_.mapping.i_gap.eqidx = [1 2 13 17 ];
M_.mapping.u_gap.eqidx = [4 13 17 ];
M_.mapping.yhat_us.eqidx = [1 5 6 17 ];
M_.mapping.pi_us_gap.eqidx = [6 17 ];
M_.mapping.ibar.eqidx = [7 17 ];
M_.mapping.pibar_au.eqidx = [3 8 17 ];
M_.mapping.pibar_us.eqidx = [9 17 ];
M_.mapping.piQ.eqidx = [3 10 17 ];
M_.mapping.pi_m.eqidx = [3 11 17 ];
M_.mapping.dln_pcom.eqidx = [3 12 17 ];
M_.mapping.piQ_hat.eqidx = [13 14 17 ];
M_.mapping.pQ_level.eqidx = [14 15 16 ];
M_.mapping.eps_q.eqidx = [1 ];
M_.mapping.eps_i.eqidx = [2 ];
M_.mapping.eps_pi.eqidx = [3 ];
M_.mapping.eps_q_us.eqidx = [5 ];
M_.mapping.eps_pi_us.eqidx = [6 ];
M_.mapping.eps_ibar.eqidx = [7 ];
M_.mapping.eps_pibar_au.eqidx = [8 ];
M_.mapping.eps_pibar_us.eqidx = [9 ];
M_.mapping.eps_u_gap.eqidx = [4 ];
M_.mapping.eps_piQ.eqidx = [10 ];
M_.mapping.eps_pi_m.eqidx = [11 ];
M_.mapping.eps_pcom.eqidx = [12 ];
M_.mapping.eps_var_pQ.eqidx = [13 ];
M_.mapping.eps_pQ.eqidx = [14 ];
M_.mapping.pac_expectation_pac_pQ.eqidx = [14 17 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = true;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 17;
M_.block_structure.block(1).mfs = 17;
M_.block_structure.block(1).equation = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 16 17 14 15];
M_.block_structure.block(1).variable = [ 1 3 2 4 5 6 7 8 9 10 11 12 13 16 17 15 14];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 21;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 6 7 8 9 10 11 12 13 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 1 3 2 4 5 6 7 8 9 10 11 12 13 16 17 15 14];
M_.block_structure.equation_reordered = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 16 17 14 15];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 5;
 2 1;
 2 2;
 2 3;
 3 1;
 3 2;
 3 8;
 3 10;
 3 11;
 3 12;
 4 1;
 4 4;
 5 5;
 6 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 1;
 13 2;
 13 3;
 13 4;
 13 13;
 14 13;
 14 14;
 15 14;
 16 15;
 17 1;
 17 2;
 17 3;
 17 4;
 17 5;
 17 6;
 17 7;
 17 8;
 17 9;
 17 10;
 17 11;
 17 12;
 17 13;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 2 3;
 3 2;
 4 4;
 5 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 13;
 14 1;
 14 15;
 14 16;
 14 17;
 15 14;
 15 15;
 16 16;
 17 17;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [1 3 2 4 5 6 7 8 9 10 11 12 13 15 14 ];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(17, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(14, 1);
M_.params = NaN(48, 1);
M_.endo_trends = struct('deflator', cell(17, 1), 'log_deflator', cell(17, 1), 'growth_factor', cell(17, 1), 'log_growth_factor', cell(17, 1));
M_.NNZDerivatives = [81; 0; -1; ];
M_.dynamic_g1_sparse_rowval = int32([1 2 3 4 13 17 1 2 3 13 17 1 2 13 17 4 13 17 1 5 6 17 6 17 7 17 3 8 17 9 17 3 10 17 3 11 17 3 12 17 13 14 17 14 15 16 1 14 3 2 4 5 6 7 8 9 10 11 12 13 15 14 15 14 16 14 17 1 2 3 5 6 7 8 9 4 10 11 12 13 14 ]);
M_.dynamic_g1_sparse_colval = int32([1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 4 4 4 5 5 5 5 6 6 7 7 8 8 8 9 9 10 10 10 11 11 11 12 12 12 13 13 13 14 14 15 18 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 32 33 33 34 34 52 53 54 55 56 57 58 59 60 61 62 63 64 65 ]);
M_.dynamic_g1_sparse_colptr = int32([1 7 12 16 19 23 25 27 30 32 35 38 41 44 46 47 47 47 49 50 51 52 53 54 55 56 57 58 59 60 61 62 64 66 68 68 68 68 68 68 68 68 68 68 68 68 68 68 68 68 68 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'yhat_au'; 
'i_gap'; 
'pi_au_gap'; 
'u_gap'; 
'yhat_us'; 
'pi_us_gap'; 
'ibar'; 
'pibar_au'; 
'pibar_us'; 
'piQ'; 
'pi_m'; 
'dln_pcom'; 
'piQ_hat'; 
'AUX_DIFF_165'; 
'AUX_DIFF_165'; 
'AUX_DIFF_LAG_168'; 
'pac_expectation_pac_pQ'; 
};
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 3;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 5];
M_.block_structure_stat.block(1).variable = [ 5];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 6];
M_.block_structure_stat.block(2).variable = [ 6];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 7];
M_.block_structure_stat.block(3).variable = [ 7];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 8];
M_.block_structure_stat.block(4).variable = [ 8];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 9];
M_.block_structure_stat.block(5).variable = [ 9];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 10];
M_.block_structure_stat.block(6).variable = [ 10];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 11];
M_.block_structure_stat.block(7).variable = [ 11];
M_.block_structure_stat.block(8).Simulation_Type = 3;
M_.block_structure_stat.block(8).endo_nbr = 1;
M_.block_structure_stat.block(8).mfs = 1;
M_.block_structure_stat.block(8).equation = [ 12];
M_.block_structure_stat.block(8).variable = [ 12];
M_.block_structure_stat.block(9).Simulation_Type = 1;
M_.block_structure_stat.block(9).endo_nbr = 2;
M_.block_structure_stat.block(9).mfs = 2;
M_.block_structure_stat.block(9).equation = [ 15 16];
M_.block_structure_stat.block(9).variable = [ 15 16];
M_.block_structure_stat.block(10).Simulation_Type = 6;
M_.block_structure_stat.block(10).endo_nbr = 3;
M_.block_structure_stat.block(10).mfs = 3;
M_.block_structure_stat.block(10).equation = [ 3 2 1];
M_.block_structure_stat.block(10).variable = [ 1 3 2];
M_.block_structure_stat.block(11).Simulation_Type = 3;
M_.block_structure_stat.block(11).endo_nbr = 1;
M_.block_structure_stat.block(11).mfs = 1;
M_.block_structure_stat.block(11).equation = [ 4];
M_.block_structure_stat.block(11).variable = [ 4];
M_.block_structure_stat.block(12).Simulation_Type = 3;
M_.block_structure_stat.block(12).endo_nbr = 1;
M_.block_structure_stat.block(12).mfs = 1;
M_.block_structure_stat.block(12).equation = [ 13];
M_.block_structure_stat.block(12).variable = [ 13];
M_.block_structure_stat.block(13).Simulation_Type = 1;
M_.block_structure_stat.block(13).endo_nbr = 1;
M_.block_structure_stat.block(13).mfs = 1;
M_.block_structure_stat.block(13).equation = [ 17];
M_.block_structure_stat.block(13).variable = [ 17];
M_.block_structure_stat.block(14).Simulation_Type = 3;
M_.block_structure_stat.block(14).endo_nbr = 1;
M_.block_structure_stat.block(14).mfs = 1;
M_.block_structure_stat.block(14).equation = [ 14];
M_.block_structure_stat.block(14).variable = [ 14];
M_.block_structure_stat.variable_reordered = [ 5 6 7 8 9 10 11 12 15 16 1 3 2 4 13 17 14];
M_.block_structure_stat.equation_reordered = [ 5 6 7 8 9 10 11 12 15 16 3 2 1 4 13 17 14];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 5;
 2 1;
 2 2;
 2 3;
 3 1;
 3 2;
 3 8;
 3 10;
 3 11;
 3 12;
 4 1;
 4 4;
 5 5;
 6 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 1;
 13 2;
 13 3;
 13 4;
 13 13;
 14 1;
 14 13;
 14 14;
 14 15;
 14 16;
 14 17;
 15 15;
 16 15;
 16 16;
 17 1;
 17 2;
 17 3;
 17 4;
 17 5;
 17 6;
 17 7;
 17 8;
 17 9;
 17 10;
 17 11;
 17 12;
 17 13;
 17 17;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(8).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(9).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(9).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(9).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(10).g1_sparse_rowval = int32([1 2 3 2 3 1 2 3 ]);
M_.block_structure_stat.block(10).g1_sparse_colval = int32([1 1 1 2 2 3 3 3 ]);
M_.block_structure_stat.block(10).g1_sparse_colptr = int32([1 4 6 9 ]);
M_.block_structure_stat.block(11).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(12).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(13).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(13).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(13).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(14).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(14).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(14).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 2 3 4 13 14 17 1 2 3 13 17 1 2 13 17 4 13 17 1 5 6 17 6 17 7 17 3 8 17 9 17 3 10 17 3 11 17 3 12 17 13 14 17 14 14 15 16 14 16 14 17 ]);
M_.static_g1_sparse_colval = int32([1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 4 4 4 5 5 5 5 6 6 7 7 8 8 8 9 9 10 10 10 11 11 11 12 12 12 13 13 13 14 15 15 15 16 16 17 17 ]);
M_.static_g1_sparse_colptr = int32([1 8 13 17 20 24 26 28 31 33 36 39 42 45 46 49 51 53 ]);
M_.params(1) = 0.1989;
delta = M_.params(1);
M_.params(2) = 0.6959;
lambda_q = M_.params(2);
M_.params(3) = 0.0648;
sigma_q = M_.params(3);
M_.params(4) = 0.9576;
lambda_i = M_.params(4);
M_.params(5) = 0.3001;
alpha_i = M_.params(5);
M_.params(6) = 0.0837;
beta_i = M_.params(6);
M_.params(7) = 0.2902;
lambda_pi = M_.params(7);
M_.params(8) = 0.0374;
kappa_pi = M_.params(8);
M_.params(9) = 0.8057;
lambda_q_us = M_.params(9);
M_.params(10) = 0.6529;
lambda_pi_us = M_.params(10);
M_.params(11) = 0.0131;
kappa_pi_us = M_.params(11);
M_.params(12) = 0.985;
lambda_ibar = M_.params(12);
M_.params(13) = 0.93;
lambda_pibar = M_.params(13);
M_.params(14) = 0.93;
lambda_pibar_us = M_.params(14);
M_.params(15) = 0.94;
rho_u_gap = M_.params(15);
M_.params(16) = (-0.33);
okun_coeff = M_.params(16);
M_.params(17) = 0.17;
alpha_pc = M_.params(17);
M_.params(18) = 0.10;
beta_pc_m = M_.params(18);
M_.params(19) = 0.03;
gamma_oil = M_.params(19);
M_.params(20) = 1.0491;
i_ss = M_.params(20);
M_.params(21) = 0.625;
pi_ss_au = M_.params(21);
M_.params(22) = 0.5;
pi_ss_us = M_.params(22);
M_.params(23) = 0.85;
rho_pQ_aux = M_.params(23);
M_.params(24) = 0.05;
a_pQ_y = M_.params(24);
M_.params(25) = 0.0;
a_pQ_i = M_.params(25);
M_.params(26) = 0.0;
a_pQ_pi = M_.params(26);
M_.params(27) = 0.0;
a_pQ_u = M_.params(27);
M_.params(28) = 0.85;
rho_piQ = M_.params(28);
M_.params(29) = 0.7;
rho_pi_m = M_.params(29);
M_.params(30) = 0.42;
rho_pcom = M_.params(30);
M_.params(31) = 0.0294;
b0_pQ = M_.params(31);
M_.params(32) = 0.2784;
b1_pQ = M_.params(32);
M_.params(33) = 0.0022;
b2_pQ = M_.params(33);
M_.params(34) = 0.98;
beta_pac = M_.params(34);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.527)^2;
M_.Sigma_e(2, 2) = (0.110)^2;
M_.Sigma_e(3, 3) = (0.590)^2;
M_.Sigma_e(4, 4) = (1.138)^2;
M_.Sigma_e(5, 5) = (0.319)^2;
M_.Sigma_e(6, 6) = (0.01)^2;
M_.Sigma_e(7, 7) = (0.01)^2;
M_.Sigma_e(8, 8) = (0.01)^2;
M_.Sigma_e(9, 9) = (0.05)^2;
M_.Sigma_e(10, 10) = (0.571)^2;
M_.Sigma_e(11, 11) = (0.5)^2;
M_.Sigma_e(12, 12) = (3.0)^2;
M_.Sigma_e(13, 13) = (0.01)^2;
M_.Sigma_e(14, 14) = (0.571)^2;
pac.initialize('pac_pQ');
pac.update.expectation('pac_pQ');
pac.print('pac_pQ', 'eq_piQ_pac');


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_pQ_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
