%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'test_var_pac';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(5,1);
M_.exo_names_tex = cell(5,1);
M_.exo_names_long = cell(5,1);
M_.exo_names(1) = {'eps_y'};
M_.exo_names_tex(1) = {'eps\_y'};
M_.exo_names_long(1) = {'eps_y'};
M_.exo_names(2) = {'eps_i'};
M_.exo_names_tex(2) = {'eps\_i'};
M_.exo_names_long(2) = {'eps_i'};
M_.exo_names(3) = {'eps_pi'};
M_.exo_names_tex(3) = {'eps\_pi'};
M_.exo_names_long(3) = {'eps_pi'};
M_.exo_names(4) = {'eps_pQ_aux'};
M_.exo_names_tex(4) = {'eps\_pQ\_aux'};
M_.exo_names_long(4) = {'eps_pQ_aux'};
M_.exo_names(5) = {'eps_pQ'};
M_.exo_names_tex(5) = {'eps\_pQ'};
M_.exo_names_long(5) = {'eps_pQ'};
M_.endo_names = cell(9,1);
M_.endo_names_tex = cell(9,1);
M_.endo_names_long = cell(9,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'y\_gap'};
M_.endo_names_long(1) = {'y_gap'};
M_.endo_names(2) = {'i_gap'};
M_.endo_names_tex(2) = {'i\_gap'};
M_.endo_names_long(2) = {'i_gap'};
M_.endo_names(3) = {'pi_gap'};
M_.endo_names_tex(3) = {'pi\_gap'};
M_.endo_names_long(3) = {'pi_gap'};
M_.endo_names(4) = {'piQ_star_hat'};
M_.endo_names_tex(4) = {'piQ\_star\_hat'};
M_.endo_names_long(4) = {'piQ_star_hat'};
M_.endo_names(5) = {'piQ'};
M_.endo_names_tex(5) = {'piQ'};
M_.endo_names_long(5) = {'piQ'};
M_.endo_names(6) = {'pQ_level'};
M_.endo_names_tex(6) = {'pQ\_level'};
M_.endo_names_long(6) = {'pQ_level'};
M_.endo_names(7) = {'AUX_DIFF_61'};
M_.endo_names_tex(7) = {'AUX\_DIFF\_61'};
M_.endo_names_long(7) = {'AUX_DIFF_61'};
M_.endo_names(8) = {'AUX_DIFF_LAG_62'};
M_.endo_names_tex(8) = {'AUX\_DIFF\_LAG\_62'};
M_.endo_names_long(8) = {'AUX_DIFF_LAG_62'};
M_.endo_names(9) = {'pac_expectation_pac_piQ'};
M_.endo_names_tex(9) = {'pac\_expectation\_pac\_piQ'};
M_.endo_names_long(9) = {'pac_expectation_pac_piQ'};
M_.endo_partitions = struct();
M_.param_names = cell(21,1);
M_.param_names_tex = cell(21,1);
M_.param_names_long = cell(21,1);
M_.param_names(1) = {'lambda_q'};
M_.param_names_tex(1) = {'lambda\_q'};
M_.param_names_long(1) = {'lambda_q'};
M_.param_names(2) = {'sigma_q'};
M_.param_names_tex(2) = {'sigma\_q'};
M_.param_names_long(2) = {'sigma_q'};
M_.param_names(3) = {'lambda_i'};
M_.param_names_tex(3) = {'lambda\_i'};
M_.param_names_long(3) = {'lambda_i'};
M_.param_names(4) = {'alpha_i'};
M_.param_names_tex(4) = {'alpha\_i'};
M_.param_names_long(4) = {'alpha_i'};
M_.param_names(5) = {'beta_i_par'};
M_.param_names_tex(5) = {'beta\_i\_par'};
M_.param_names_long(5) = {'beta_i_par'};
M_.param_names(6) = {'lambda_pi'};
M_.param_names_tex(6) = {'lambda\_pi'};
M_.param_names_long(6) = {'lambda_pi'};
M_.param_names(7) = {'kappa_pi'};
M_.param_names_tex(7) = {'kappa\_pi'};
M_.param_names_long(7) = {'kappa_pi'};
M_.param_names(8) = {'rho_pQ_hat'};
M_.param_names_tex(8) = {'rho\_pQ\_hat'};
M_.param_names_long(8) = {'rho_pQ_hat'};
M_.param_names(9) = {'a_pQ_y'};
M_.param_names_tex(9) = {'a\_pQ\_y'};
M_.param_names_long(9) = {'a_pQ_y'};
M_.param_names(10) = {'a_pQ_i'};
M_.param_names_tex(10) = {'a\_pQ\_i'};
M_.param_names_long(10) = {'a_pQ_i'};
M_.param_names(11) = {'a_pQ_pi'};
M_.param_names_tex(11) = {'a\_pQ\_pi'};
M_.param_names_long(11) = {'a_pQ_pi'};
M_.param_names(12) = {'b0_pQ'};
M_.param_names_tex(12) = {'b0\_pQ'};
M_.param_names_long(12) = {'b0_pQ'};
M_.param_names(13) = {'b1_pQ'};
M_.param_names_tex(13) = {'b1\_pQ'};
M_.param_names_long(13) = {'b1_pQ'};
M_.param_names(14) = {'b2_pQ'};
M_.param_names_tex(14) = {'b2\_pQ'};
M_.param_names_long(14) = {'b2_pQ'};
M_.param_names(15) = {'beta_pac'};
M_.param_names_tex(15) = {'beta\_pac'};
M_.param_names_long(15) = {'beta_pac'};
M_.param_names(16) = {'pi_ss'};
M_.param_names_tex(16) = {'pi\_ss'};
M_.param_names_long(16) = {'pi_ss'};
M_.param_names(17) = {'h_pac_piQ_constant'};
M_.param_names_tex(17) = {'h\_pac\_piQ\_constant'};
M_.param_names_long(17) = {'h_pac_piQ_constant'};
M_.param_names(18) = {'h_pac_piQ_var_y_gap_lag_1'};
M_.param_names_tex(18) = {'h\_pac\_piQ\_var\_y\_gap\_lag\_1'};
M_.param_names_long(18) = {'h_pac_piQ_var_y_gap_lag_1'};
M_.param_names(19) = {'h_pac_piQ_var_i_gap_lag_1'};
M_.param_names_tex(19) = {'h\_pac\_piQ\_var\_i\_gap\_lag\_1'};
M_.param_names_long(19) = {'h_pac_piQ_var_i_gap_lag_1'};
M_.param_names(20) = {'h_pac_piQ_var_pi_gap_lag_1'};
M_.param_names_tex(20) = {'h\_pac\_piQ\_var\_pi\_gap\_lag\_1'};
M_.param_names_long(20) = {'h_pac_piQ_var_pi_gap_lag_1'};
M_.param_names(21) = {'h_pac_piQ_var_piQ_star_hat_lag_1'};
M_.param_names_tex(21) = {'h\_pac\_piQ\_var\_piQ\_star\_hat\_lag\_1'};
M_.param_names_long(21) = {'h_pac_piQ_var_piQ_star_hat_lag_1'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 9;
M_.param_nbr = 21;
M_.orig_endo_nbr = 6;
M_.aux_vars(1).endo_index = 7;
M_.aux_vars(1).type = 8;
M_.aux_vars(1).orig_index = 6;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'diff(pQ_level)';
M_.aux_vars(2).endo_index = 8;
M_.aux_vars(2).type = 9;
M_.aux_vars(2).orig_index = 7;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'diff(pQ_level(-1))';
M_.aux_vars(3).endo_index = 9;
M_.aux_vars(3).type = 12;
M_.aux_vars(3).orig_expr = 'h_pac_piQ_constant+y_gap(-1)*h_pac_piQ_var_y_gap_lag_1+i_gap(-1)*h_pac_piQ_var_i_gap_lag_1+pi_gap(-1)*h_pac_piQ_var_pi_gap_lag_1+piQ_star_hat(-1)*h_pac_piQ_var_piQ_star_hat_lag_1';
M_.var.esat_enriched.model_name = 'esat_enriched';
M_.var.esat_enriched.structural = false;
M_.var.esat_enriched.eqtags = {'var_y'; 'var_i'; 'var_pi'; 'var_pQ_hat'; };
M_.var.esat_enriched.eqn = [1 2 3 4 ];
M_.var.esat_enriched.lhs = [1 2 3 4 ];
M_.var.esat_enriched.max_lag = [1 1 1 1 ];
M_.var.esat_enriched.diff = [false false false false ];
M_.var.esat_enriched.nonstationary = M_.var.esat_enriched.diff;
M_.var.esat_enriched.orig_diff_var = [-1 -1 -1 -1 ];
M_.var.esat_enriched.rhs.vars_at_eq{1}.var = [1 2 3 ];
M_.var.esat_enriched.rhs.vars_at_eq{1}.lag = [-1 -1 -1 ];
M_.var.esat_enriched.rhs.vars_at_eq{2}.var = [1 2 3 ];
M_.var.esat_enriched.rhs.vars_at_eq{2}.lag = [-1 -1 -1 ];
M_.var.esat_enriched.rhs.vars_at_eq{3}.var = [1 3 ];
M_.var.esat_enriched.rhs.vars_at_eq{3}.lag = [-1 -1 ];
M_.var.esat_enriched.rhs.vars_at_eq{4}.var = [1 2 3 4 ];
M_.var.esat_enriched.rhs.vars_at_eq{4}.lag = [-1 -1 -1 -1 ];
M_.pac.pac_piQ.auxiliary_model_name = 'esat_enriched';
M_.pac.pac_piQ.discount_index = 15;
M_.pac.pac_piQ.h_param_indices = [17 18 19 20 21 ];
M_.pac.pac_piQ.aux_id = 9;
M_.pac.pac_piQ.eq_name = 'eq_piQ_pac';
M_.pac.pac_piQ.auxiliary_model_type = 'var';
M_.pac.pac_piQ.kind = '';
M_.pac.pac_piQ.lhs_var = 7;
M_.pac.pac_piQ.ec.params = 12;
M_.pac.pac_piQ.ec.vars = [4 6 ];
M_.pac.pac_piQ.ec.istarget = [true false ];
M_.pac.pac_piQ.ec.scale = [1 -1 ];
M_.pac.pac_piQ.ec.isendo = [true true ];
M_.pac.pac_piQ.ar.params = [13 ];
M_.pac.pac_piQ.ar.vars = [8 ];
M_.pac.pac_piQ.ar.lags = [0 ];
M_.pac.pac_piQ.max_lag = 1;
M_.pac.pac_piQ.additive.params = [NaN 14 ];
M_.pac.pac_piQ.additive.vars = [5 1 ];
M_.pac.pac_piQ.additive.isendo = [false true ];
M_.pac.pac_piQ.additive.lags = [0 0 ];
M_.pac.pac_piQ.additive.scaling_factor = [1 1 ];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.eq_nbr = 9;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 0;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 0;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 1 7;
 2 8;
 3 9;
 4 10;
 0 11;
 5 12;
 6 13;
 0 14;
 0 15;]';
M_.nstatic = 3;
M_.nfwrd   = 0;
M_.npred   = 6;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 6;
M_.ndynamic   = 6;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'var_y' ;
  2 , 'name' , 'var_i' ;
  3 , 'name' , 'var_pi' ;
  4 , 'name' , 'var_pQ_hat' ;
  5 , 'name' , 'eq_pQ_level' ;
  6 , 'name' , 'eq_piQ_pac' ;
};
M_.mapping.y_gap.eqidx = [1 2 3 4 6 9 ];
M_.mapping.i_gap.eqidx = [1 2 4 9 ];
M_.mapping.pi_gap.eqidx = [1 2 3 4 9 ];
M_.mapping.piQ_star_hat.eqidx = [4 6 9 ];
M_.mapping.piQ.eqidx = [5 ];
M_.mapping.pQ_level.eqidx = [5 6 7 8 ];
M_.mapping.eps_y.eqidx = [1 ];
M_.mapping.eps_i.eqidx = [2 ];
M_.mapping.eps_pi.eqidx = [3 ];
M_.mapping.eps_pQ_aux.eqidx = [4 ];
M_.mapping.eps_pQ.eqidx = [6 ];
M_.mapping.pac_expectation_pac_piQ.eqidx = [6 9 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = true;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 9;
M_.block_structure.block(1).mfs = 9;
M_.block_structure.block(1).equation = [ 1 2 3 4 8 9 6 7 5];
M_.block_structure.block(1).variable = [ 1 2 3 4 8 9 7 6 5];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 14;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 7 8 10 11 12 13 14 15 16 17 18 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 1 2 3 4 8 9 7 6 5];
M_.block_structure.equation_reordered = [ 1 2 3 4 8 9 6 7 5];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 1;
 1 2;
 1 3;
 2 1;
 2 2;
 2 3;
 3 1;
 3 3;
 4 1;
 4 2;
 4 3;
 4 4;
 5 6;
 6 4;
 6 6;
 7 6;
 8 7;
 9 1;
 9 2;
 9 3;
 9 4;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 2 2;
 3 3;
 4 4;
 5 5;
 5 6;
 6 1;
 6 7;
 6 8;
 6 9;
 7 6;
 7 7;
 8 8;
 9 9;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [1 2 3 4 7 6 ];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(9, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(21, 1);
M_.endo_trends = struct('deflator', cell(9, 1), 'log_deflator', cell(9, 1), 'growth_factor', cell(9, 1), 'log_growth_factor', cell(9, 1));
M_.NNZDerivatives = [40; -1; -1; ];
M_.dynamic_g1_sparse_rowval = int32([1 2 3 4 9 1 2 4 9 1 2 3 4 9 4 6 9 5 6 7 8 1 6 2 3 4 5 5 7 6 7 6 8 6 9 1 2 3 4 6 ]);
M_.dynamic_g1_sparse_colval = int32([1 1 1 1 1 2 2 2 2 3 3 3 3 3 4 4 4 6 6 6 7 10 10 11 12 13 14 15 15 16 16 17 17 18 18 28 29 30 31 32 ]);
M_.dynamic_g1_sparse_colptr = int32([1 6 10 15 18 18 21 22 22 22 24 25 26 27 28 30 32 34 36 36 36 36 36 36 36 36 36 36 37 38 39 40 41 ]);
M_.lhs = {
'y_gap'; 
'i_gap'; 
'pi_gap'; 
'piQ_star_hat'; 
'pQ_level'; 
'AUX_DIFF_61'; 
'AUX_DIFF_61'; 
'AUX_DIFF_LAG_62'; 
'pac_expectation_pac_piQ'; 
};
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 2;
M_.block_structure_stat.block(1).mfs = 2;
M_.block_structure_stat.block(1).equation = [ 7 8];
M_.block_structure_stat.block(1).variable = [ 7 8];
M_.block_structure_stat.block(2).Simulation_Type = 6;
M_.block_structure_stat.block(2).endo_nbr = 3;
M_.block_structure_stat.block(2).mfs = 3;
M_.block_structure_stat.block(2).equation = [ 3 2 1];
M_.block_structure_stat.block(2).variable = [ 3 1 2];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 4];
M_.block_structure_stat.block(3).variable = [ 4];
M_.block_structure_stat.block(4).Simulation_Type = 1;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 9];
M_.block_structure_stat.block(4).variable = [ 9];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 6];
M_.block_structure_stat.block(5).variable = [ 6];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 5];
M_.block_structure_stat.block(6).variable = [ 5];
M_.block_structure_stat.variable_reordered = [ 7 8 3 1 2 4 9 6 5];
M_.block_structure_stat.equation_reordered = [ 7 8 3 2 1 4 9 6 5];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 3;
 2 1;
 2 2;
 2 3;
 3 1;
 3 3;
 4 1;
 4 2;
 4 3;
 4 4;
 5 5;
 6 1;
 6 4;
 6 6;
 6 7;
 6 8;
 6 9;
 7 7;
 8 7;
 8 8;
 9 1;
 9 2;
 9 3;
 9 4;
 9 9;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 2 3 1 2 3 2 3 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 1 1 2 2 2 3 3 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 4 7 9 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 2 3 4 6 9 1 2 4 9 1 2 3 4 9 4 6 9 5 6 6 7 8 6 8 6 9 ]);
M_.static_g1_sparse_colval = int32([1 1 1 1 1 1 2 2 2 2 3 3 3 3 3 4 4 4 5 6 7 7 7 8 8 9 9 ]);
M_.static_g1_sparse_colptr = int32([1 7 11 16 19 20 21 24 26 28 ]);
M_.params(1) = 0.45;
lambda_q = M_.params(1);
M_.params(2) = 0.17;
sigma_q = M_.params(2);
M_.params(3) = 0.83;
lambda_i = M_.params(3);
M_.params(4) = 0.28;
alpha_i = M_.params(4);
M_.params(5) = 0.14;
beta_i_par = M_.params(5);
M_.params(6) = 0.26;
lambda_pi = M_.params(6);
M_.params(7) = 0.06;
kappa_pi = M_.params(7);
M_.params(8) = 0.70;
rho_pQ_hat = M_.params(8);
M_.params(9) = 0.08;
a_pQ_y = M_.params(9);
M_.params(10) = (-0.03);
a_pQ_i = M_.params(10);
M_.params(11) = 0.02;
a_pQ_pi = M_.params(11);
M_.params(12) = 0.06;
b0_pQ = M_.params(12);
M_.params(13) = 0.50;
b1_pQ = M_.params(13);
M_.params(14) = 0.09;
b2_pQ = M_.params(14);
M_.params(15) = 0.98;
beta_pac = M_.params(15);
M_.params(16) = 0.00;
pi_ss = M_.params(16);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.34)^2;
M_.Sigma_e(2, 2) = (0.10)^2;
M_.Sigma_e(3, 3) = (0.26)^2;
M_.Sigma_e(4, 4) = (0.50)^2;
M_.Sigma_e(5, 5) = (0.50)^2;
pac.initialize('pac_piQ');
pac.update.expectation('pac_piQ');
options_.irf = 40;
options_.nograph = true;
options_.order = 1;
var_list_ = {'y_gap';'i_gap';'pi_gap';'piQ';'piQ_star_hat'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
