%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'aux_business_inv';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(15,1);
M_.exo_names_tex = cell(15,1);
M_.exo_names_long = cell(15,1);
M_.exo_names(1) = {'eps_q'};
M_.exo_names_tex(1) = {'eps\_q'};
M_.exo_names_long(1) = {'eps_q'};
M_.exo_names(2) = {'eps_i'};
M_.exo_names_tex(2) = {'eps\_i'};
M_.exo_names_long(2) = {'eps_i'};
M_.exo_names(3) = {'eps_pi'};
M_.exo_names_tex(3) = {'eps\_pi'};
M_.exo_names_long(3) = {'eps_pi'};
M_.exo_names(4) = {'eps_q_us'};
M_.exo_names_tex(4) = {'eps\_q\_us'};
M_.exo_names_long(4) = {'eps_q_us'};
M_.exo_names(5) = {'eps_pi_us'};
M_.exo_names_tex(5) = {'eps\_pi\_us'};
M_.exo_names_long(5) = {'eps_pi_us'};
M_.exo_names(6) = {'eps_ibar'};
M_.exo_names_tex(6) = {'eps\_ibar'};
M_.exo_names_long(6) = {'eps_ibar'};
M_.exo_names(7) = {'eps_pibar_au'};
M_.exo_names_tex(7) = {'eps\_pibar\_au'};
M_.exo_names_long(7) = {'eps_pibar_au'};
M_.exo_names(8) = {'eps_pibar_us'};
M_.exo_names_tex(8) = {'eps\_pibar\_us'};
M_.exo_names_long(8) = {'eps_pibar_us'};
M_.exo_names(9) = {'eps_u_gap'};
M_.exo_names_tex(9) = {'eps\_u\_gap'};
M_.exo_names_long(9) = {'eps_u_gap'};
M_.exo_names(10) = {'eps_piQ'};
M_.exo_names_tex(10) = {'eps\_piQ'};
M_.exo_names_long(10) = {'eps_piQ'};
M_.exo_names(11) = {'eps_pi_m'};
M_.exo_names_tex(11) = {'eps\_pi\_m'};
M_.exo_names_long(11) = {'eps_pi_m'};
M_.exo_names(12) = {'eps_pcom'};
M_.exo_names_tex(12) = {'eps\_pcom'};
M_.exo_names_long(12) = {'eps_pcom'};
M_.exo_names(13) = {'eps_var_ib'};
M_.exo_names_tex(13) = {'eps\_var\_ib'};
M_.exo_names_long(13) = {'eps_var_ib'};
M_.exo_names(14) = {'eps_var_rKB'};
M_.exo_names_tex(14) = {'eps\_var\_rKB'};
M_.exo_names_long(14) = {'eps_var_rKB'};
M_.exo_names(15) = {'eps_ib'};
M_.exo_names_tex(15) = {'eps\_ib'};
M_.exo_names_long(15) = {'eps_ib'};
M_.endo_names = cell(19,1);
M_.endo_names_tex = cell(19,1);
M_.endo_names_long = cell(19,1);
M_.endo_names(1) = {'yhat_au'};
M_.endo_names_tex(1) = {'yhat\_au'};
M_.endo_names_long(1) = {'yhat_au'};
M_.endo_names(2) = {'pi_au_gap'};
M_.endo_names_tex(2) = {'pi\_au\_gap'};
M_.endo_names_long(2) = {'pi_au_gap'};
M_.endo_names(3) = {'i_gap'};
M_.endo_names_tex(3) = {'i\_gap'};
M_.endo_names_long(3) = {'i_gap'};
M_.endo_names(4) = {'u_gap'};
M_.endo_names_tex(4) = {'u\_gap'};
M_.endo_names_long(4) = {'u_gap'};
M_.endo_names(5) = {'yhat_us'};
M_.endo_names_tex(5) = {'yhat\_us'};
M_.endo_names_long(5) = {'yhat_us'};
M_.endo_names(6) = {'pi_us_gap'};
M_.endo_names_tex(6) = {'pi\_us\_gap'};
M_.endo_names_long(6) = {'pi_us_gap'};
M_.endo_names(7) = {'ibar'};
M_.endo_names_tex(7) = {'ibar'};
M_.endo_names_long(7) = {'ibar'};
M_.endo_names(8) = {'pibar_au'};
M_.endo_names_tex(8) = {'pibar\_au'};
M_.endo_names_long(8) = {'pibar_au'};
M_.endo_names(9) = {'pibar_us'};
M_.endo_names_tex(9) = {'pibar\_us'};
M_.endo_names_long(9) = {'pibar_us'};
M_.endo_names(10) = {'piQ'};
M_.endo_names_tex(10) = {'piQ'};
M_.endo_names_long(10) = {'piQ'};
M_.endo_names(11) = {'pi_m'};
M_.endo_names_tex(11) = {'pi\_m'};
M_.endo_names_long(11) = {'pi_m'};
M_.endo_names(12) = {'dln_pcom'};
M_.endo_names_tex(12) = {'dln\_pcom'};
M_.endo_names_long(12) = {'dln_pcom'};
M_.endo_names(13) = {'ib_hat'};
M_.endo_names_tex(13) = {'ib\_hat'};
M_.endo_names_long(13) = {'ib_hat'};
M_.endo_names(14) = {'rKB_hat'};
M_.endo_names_tex(14) = {'rKB\_hat'};
M_.endo_names_long(14) = {'rKB_hat'};
M_.endo_names(15) = {'ln_ib_level'};
M_.endo_names_tex(15) = {'ln\_ib\_level'};
M_.endo_names_long(15) = {'ln_ib_level'};
M_.endo_names(16) = {'AUX_DIFF_172'};
M_.endo_names_tex(16) = {'AUX\_DIFF\_172'};
M_.endo_names_long(16) = {'AUX_DIFF_172'};
M_.endo_names(17) = {'AUX_DIFF_LAG_175'};
M_.endo_names_tex(17) = {'AUX\_DIFF\_LAG\_175'};
M_.endo_names_long(17) = {'AUX_DIFF_LAG_175'};
M_.endo_names(18) = {'AUX_DIFF_LAG_184'};
M_.endo_names_tex(18) = {'AUX\_DIFF\_LAG\_184'};
M_.endo_names_long(18) = {'AUX_DIFF_LAG_184'};
M_.endo_names(19) = {'pac_expectation_pac_ib'};
M_.endo_names_tex(19) = {'pac\_expectation\_pac\_ib'};
M_.endo_names_long(19) = {'pac_expectation_pac_ib'};
M_.endo_partitions = struct();
M_.param_names = cell(51,1);
M_.param_names_tex = cell(51,1);
M_.param_names_long = cell(51,1);
M_.param_names(1) = {'delta'};
M_.param_names_tex(1) = {'delta'};
M_.param_names_long(1) = {'delta'};
M_.param_names(2) = {'lambda_q'};
M_.param_names_tex(2) = {'lambda\_q'};
M_.param_names_long(2) = {'lambda_q'};
M_.param_names(3) = {'sigma_q'};
M_.param_names_tex(3) = {'sigma\_q'};
M_.param_names_long(3) = {'sigma_q'};
M_.param_names(4) = {'lambda_i'};
M_.param_names_tex(4) = {'lambda\_i'};
M_.param_names_long(4) = {'lambda_i'};
M_.param_names(5) = {'alpha_i'};
M_.param_names_tex(5) = {'alpha\_i'};
M_.param_names_long(5) = {'alpha_i'};
M_.param_names(6) = {'beta_i'};
M_.param_names_tex(6) = {'beta\_i'};
M_.param_names_long(6) = {'beta_i'};
M_.param_names(7) = {'lambda_pi'};
M_.param_names_tex(7) = {'lambda\_pi'};
M_.param_names_long(7) = {'lambda_pi'};
M_.param_names(8) = {'kappa_pi'};
M_.param_names_tex(8) = {'kappa\_pi'};
M_.param_names_long(8) = {'kappa_pi'};
M_.param_names(9) = {'lambda_q_us'};
M_.param_names_tex(9) = {'lambda\_q\_us'};
M_.param_names_long(9) = {'lambda_q_us'};
M_.param_names(10) = {'lambda_pi_us'};
M_.param_names_tex(10) = {'lambda\_pi\_us'};
M_.param_names_long(10) = {'lambda_pi_us'};
M_.param_names(11) = {'kappa_pi_us'};
M_.param_names_tex(11) = {'kappa\_pi\_us'};
M_.param_names_long(11) = {'kappa_pi_us'};
M_.param_names(12) = {'lambda_ibar'};
M_.param_names_tex(12) = {'lambda\_ibar'};
M_.param_names_long(12) = {'lambda_ibar'};
M_.param_names(13) = {'lambda_pibar'};
M_.param_names_tex(13) = {'lambda\_pibar'};
M_.param_names_long(13) = {'lambda_pibar'};
M_.param_names(14) = {'lambda_pibar_us'};
M_.param_names_tex(14) = {'lambda\_pibar\_us'};
M_.param_names_long(14) = {'lambda_pibar_us'};
M_.param_names(15) = {'rho_u_gap'};
M_.param_names_tex(15) = {'rho\_u\_gap'};
M_.param_names_long(15) = {'rho_u_gap'};
M_.param_names(16) = {'okun_coeff'};
M_.param_names_tex(16) = {'okun\_coeff'};
M_.param_names_long(16) = {'okun_coeff'};
M_.param_names(17) = {'alpha_pc'};
M_.param_names_tex(17) = {'alpha\_pc'};
M_.param_names_long(17) = {'alpha_pc'};
M_.param_names(18) = {'beta_pc_m'};
M_.param_names_tex(18) = {'beta\_pc\_m'};
M_.param_names_long(18) = {'beta_pc_m'};
M_.param_names(19) = {'gamma_oil'};
M_.param_names_tex(19) = {'gamma\_oil'};
M_.param_names_long(19) = {'gamma_oil'};
M_.param_names(20) = {'i_ss'};
M_.param_names_tex(20) = {'i\_ss'};
M_.param_names_long(20) = {'i_ss'};
M_.param_names(21) = {'pi_ss_au'};
M_.param_names_tex(21) = {'pi\_ss\_au'};
M_.param_names_long(21) = {'pi_ss_au'};
M_.param_names(22) = {'pi_ss_us'};
M_.param_names_tex(22) = {'pi\_ss\_us'};
M_.param_names_long(22) = {'pi_ss_us'};
M_.param_names(23) = {'rho_piQ'};
M_.param_names_tex(23) = {'rho\_piQ'};
M_.param_names_long(23) = {'rho_piQ'};
M_.param_names(24) = {'rho_pi_m'};
M_.param_names_tex(24) = {'rho\_pi\_m'};
M_.param_names_long(24) = {'rho_pi_m'};
M_.param_names(25) = {'rho_pcom'};
M_.param_names_tex(25) = {'rho\_pcom'};
M_.param_names_long(25) = {'rho_pcom'};
M_.param_names(26) = {'rho_ib_aux'};
M_.param_names_tex(26) = {'rho\_ib\_aux'};
M_.param_names_long(26) = {'rho_ib_aux'};
M_.param_names(27) = {'a_ib_y'};
M_.param_names_tex(27) = {'a\_ib\_y'};
M_.param_names_long(27) = {'a_ib_y'};
M_.param_names(28) = {'a_ib_pi'};
M_.param_names_tex(28) = {'a\_ib\_pi'};
M_.param_names_long(28) = {'a_ib_pi'};
M_.param_names(29) = {'a_ib_u'};
M_.param_names_tex(29) = {'a\_ib\_u'};
M_.param_names_long(29) = {'a_ib_u'};
M_.param_names(30) = {'rho_rKB_aux'};
M_.param_names_tex(30) = {'rho\_rKB\_aux'};
M_.param_names_long(30) = {'rho_rKB_aux'};
M_.param_names(31) = {'a_rKB_i'};
M_.param_names_tex(31) = {'a\_rKB\_i'};
M_.param_names_long(31) = {'a_rKB_i'};
M_.param_names(32) = {'b0_ib'};
M_.param_names_tex(32) = {'b0\_ib'};
M_.param_names_long(32) = {'b0_ib'};
M_.param_names(33) = {'b1_ib'};
M_.param_names_tex(33) = {'b1\_ib'};
M_.param_names_long(33) = {'b1_ib'};
M_.param_names(34) = {'b2_ib'};
M_.param_names_tex(34) = {'b2\_ib'};
M_.param_names_long(34) = {'b2_ib'};
M_.param_names(35) = {'b3_ib'};
M_.param_names_tex(35) = {'b3\_ib'};
M_.param_names_long(35) = {'b3_ib'};
M_.param_names(36) = {'beta_pac'};
M_.param_names_tex(36) = {'beta\_pac'};
M_.param_names_long(36) = {'beta_pac'};
M_.param_names(37) = {'h_pac_ib_constant'};
M_.param_names_tex(37) = {'h\_pac\_ib\_constant'};
M_.param_names_long(37) = {'h_pac_ib_constant'};
M_.param_names(38) = {'h_pac_ib_var_yhat_au_lag_1'};
M_.param_names_tex(38) = {'h\_pac\_ib\_var\_yhat\_au\_lag\_1'};
M_.param_names_long(38) = {'h_pac_ib_var_yhat_au_lag_1'};
M_.param_names(39) = {'h_pac_ib_var_i_gap_lag_1'};
M_.param_names_tex(39) = {'h\_pac\_ib\_var\_i\_gap\_lag\_1'};
M_.param_names_long(39) = {'h_pac_ib_var_i_gap_lag_1'};
M_.param_names(40) = {'h_pac_ib_var_pi_au_gap_lag_1'};
M_.param_names_tex(40) = {'h\_pac\_ib\_var\_pi\_au\_gap\_lag\_1'};
M_.param_names_long(40) = {'h_pac_ib_var_pi_au_gap_lag_1'};
M_.param_names(41) = {'h_pac_ib_var_u_gap_lag_1'};
M_.param_names_tex(41) = {'h\_pac\_ib\_var\_u\_gap\_lag\_1'};
M_.param_names_long(41) = {'h_pac_ib_var_u_gap_lag_1'};
M_.param_names(42) = {'h_pac_ib_var_yhat_us_lag_1'};
M_.param_names_tex(42) = {'h\_pac\_ib\_var\_yhat\_us\_lag\_1'};
M_.param_names_long(42) = {'h_pac_ib_var_yhat_us_lag_1'};
M_.param_names(43) = {'h_pac_ib_var_pi_us_gap_lag_1'};
M_.param_names_tex(43) = {'h\_pac\_ib\_var\_pi\_us\_gap\_lag\_1'};
M_.param_names_long(43) = {'h_pac_ib_var_pi_us_gap_lag_1'};
M_.param_names(44) = {'h_pac_ib_var_ibar_lag_1'};
M_.param_names_tex(44) = {'h\_pac\_ib\_var\_ibar\_lag\_1'};
M_.param_names_long(44) = {'h_pac_ib_var_ibar_lag_1'};
M_.param_names(45) = {'h_pac_ib_var_pibar_au_lag_1'};
M_.param_names_tex(45) = {'h\_pac\_ib\_var\_pibar\_au\_lag\_1'};
M_.param_names_long(45) = {'h_pac_ib_var_pibar_au_lag_1'};
M_.param_names(46) = {'h_pac_ib_var_pibar_us_lag_1'};
M_.param_names_tex(46) = {'h\_pac\_ib\_var\_pibar\_us\_lag\_1'};
M_.param_names_long(46) = {'h_pac_ib_var_pibar_us_lag_1'};
M_.param_names(47) = {'h_pac_ib_var_piQ_lag_1'};
M_.param_names_tex(47) = {'h\_pac\_ib\_var\_piQ\_lag\_1'};
M_.param_names_long(47) = {'h_pac_ib_var_piQ_lag_1'};
M_.param_names(48) = {'h_pac_ib_var_pi_m_lag_1'};
M_.param_names_tex(48) = {'h\_pac\_ib\_var\_pi\_m\_lag\_1'};
M_.param_names_long(48) = {'h_pac_ib_var_pi_m_lag_1'};
M_.param_names(49) = {'h_pac_ib_var_dln_pcom_lag_1'};
M_.param_names_tex(49) = {'h\_pac\_ib\_var\_dln\_pcom\_lag\_1'};
M_.param_names_long(49) = {'h_pac_ib_var_dln_pcom_lag_1'};
M_.param_names(50) = {'h_pac_ib_var_ib_hat_lag_1'};
M_.param_names_tex(50) = {'h\_pac\_ib\_var\_ib\_hat\_lag\_1'};
M_.param_names_long(50) = {'h_pac_ib_var_ib_hat_lag_1'};
M_.param_names(51) = {'h_pac_ib_var_rKB_hat_lag_1'};
M_.param_names_tex(51) = {'h\_pac\_ib\_var\_rKB\_hat\_lag\_1'};
M_.param_names_long(51) = {'h_pac_ib_var_rKB_hat_lag_1'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 15;
M_.endo_nbr = 19;
M_.param_nbr = 51;
M_.orig_endo_nbr = 15;
M_.aux_vars(1).endo_index = 16;
M_.aux_vars(1).type = 8;
M_.aux_vars(1).orig_index = 15;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'diff(ln_ib_level)';
M_.aux_vars(2).endo_index = 17;
M_.aux_vars(2).type = 9;
M_.aux_vars(2).orig_index = 16;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'diff(ln_ib_level(-1))';
M_.aux_vars(3).endo_index = 18;
M_.aux_vars(3).type = 9;
M_.aux_vars(3).orig_index = 17;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(3).orig_expr = 'diff(ln_ib_level(-2))';
M_.aux_vars(4).endo_index = 19;
M_.aux_vars(4).type = 12;
M_.aux_vars(4).orig_expr = 'h_pac_ib_constant+yhat_au(-1)*h_pac_ib_var_yhat_au_lag_1+i_gap(-1)*h_pac_ib_var_i_gap_lag_1+pi_au_gap(-1)*h_pac_ib_var_pi_au_gap_lag_1+u_gap(-1)*h_pac_ib_var_u_gap_lag_1+yhat_us(-1)*h_pac_ib_var_yhat_us_lag_1+pi_us_gap(-1)*h_pac_ib_var_pi_us_gap_lag_1+ibar(-1)*h_pac_ib_var_ibar_lag_1+pibar_au(-1)*h_pac_ib_var_pibar_au_lag_1+pibar_us(-1)*h_pac_ib_var_pibar_us_lag_1+piQ(-1)*h_pac_ib_var_piQ_lag_1+pi_m(-1)*h_pac_ib_var_pi_m_lag_1+dln_pcom(-1)*h_pac_ib_var_dln_pcom_lag_1+ib_hat(-1)*h_pac_ib_var_ib_hat_lag_1+rKB_hat(-1)*h_pac_ib_var_rKB_hat_lag_1';
M_.var.esat_business_inv.model_name = 'esat_business_inv';
M_.var.esat_business_inv.structural = false;
M_.var.esat_business_inv.eqtags = {'var_yhat_au'; 'var_i_gap'; 'var_pi_au_gap'; 'var_u_gap'; 'var_yhat_us'; 'var_pi_us_gap'; 'var_ibar'; 'var_pibar_au'; 'var_pibar_us'; 'var_piQ'; 'var_pi_m'; 'var_dln_pcom'; 'var_ib'; 'var_rKB'; };
M_.var.esat_business_inv.eqn = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 ];
M_.var.esat_business_inv.lhs = [1 3 2 4 5 6 7 8 9 10 11 12 13 14 ];
M_.var.esat_business_inv.max_lag = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 ];
M_.var.esat_business_inv.diff = [false false false false false false false false false false false false false false ];
M_.var.esat_business_inv.nonstationary = M_.var.esat_business_inv.diff;
M_.var.esat_business_inv.orig_diff_var = [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{1}.var = [1 2 3 5 ];
M_.var.esat_business_inv.rhs.vars_at_eq{1}.lag = [-1 -1 -1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{2}.var = [1 2 3 ];
M_.var.esat_business_inv.rhs.vars_at_eq{2}.lag = [-1 -1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{3}.var = [1 2 8 10 11 12 ];
M_.var.esat_business_inv.rhs.vars_at_eq{3}.lag = [-1 -1 -1 -1 -1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{4}.var = [1 4 ];
M_.var.esat_business_inv.rhs.vars_at_eq{4}.lag = [-1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{5}.var = [5 ];
M_.var.esat_business_inv.rhs.vars_at_eq{5}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{6}.var = [5 6 ];
M_.var.esat_business_inv.rhs.vars_at_eq{6}.lag = [-1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{7}.var = [7 ];
M_.var.esat_business_inv.rhs.vars_at_eq{7}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{8}.var = [8 ];
M_.var.esat_business_inv.rhs.vars_at_eq{8}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{9}.var = [9 ];
M_.var.esat_business_inv.rhs.vars_at_eq{9}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{10}.var = [10 ];
M_.var.esat_business_inv.rhs.vars_at_eq{10}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{11}.var = [11 ];
M_.var.esat_business_inv.rhs.vars_at_eq{11}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{12}.var = [12 ];
M_.var.esat_business_inv.rhs.vars_at_eq{12}.lag = [-1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{13}.var = [1 2 4 13 ];
M_.var.esat_business_inv.rhs.vars_at_eq{13}.lag = [-1 -1 -1 -1 ];
M_.var.esat_business_inv.rhs.vars_at_eq{14}.var = [3 14 ];
M_.var.esat_business_inv.rhs.vars_at_eq{14}.lag = [-1 -1 ];
M_.pac.pac_ib.auxiliary_model_name = 'esat_business_inv';
M_.pac.pac_ib.discount_index = 36;
M_.pac.pac_ib.h_param_indices = [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 ];
M_.pac.pac_ib.aux_id = 19;
M_.pac.pac_ib.eq_name = 'eq_dln_ib_pac';
M_.pac.pac_ib.auxiliary_model_type = 'var';
M_.pac.pac_ib.kind = '';
M_.pac.pac_ib.lhs_var = 16;
M_.pac.pac_ib.ec.params = 32;
M_.pac.pac_ib.ec.vars = [13 15 ];
M_.pac.pac_ib.ec.istarget = [true false ];
M_.pac.pac_ib.ec.scale = [1 -1 ];
M_.pac.pac_ib.ec.isendo = [true true ];
M_.pac.pac_ib.ar.params = [33 34 ];
M_.pac.pac_ib.ar.vars = [17 18 ];
M_.pac.pac_ib.ar.lags = [0 0 ];
M_.pac.pac_ib.max_lag = 2;
M_.pac.pac_ib.additive.params = [NaN 35 ];
M_.pac.pac_ib.additive.vars = [15 1 ];
M_.pac.pac_ib.additive.isendo = [false true ];
M_.pac.pac_ib.additive.lags = [0 0 ];
M_.pac.pac_ib.additive.scaling_factor = [1 1 ];
M_.Sigma_e = zeros(15, 15);
M_.Correlation_matrix = eye(15, 15);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 19;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 0;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 0;
M_.orig_maximum_lag_with_diffs_expanded = 3;
M_.lead_lag_incidence = [
 1 18;
 2 19;
 3 20;
 4 21;
 5 22;
 6 23;
 7 24;
 8 25;
 9 26;
 10 27;
 11 28;
 12 29;
 13 30;
 14 31;
 15 32;
 16 33;
 17 34;
 0 35;
 0 36;]';
M_.nstatic = 2;
M_.nfwrd   = 0;
M_.npred   = 17;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 17;
M_.ndynamic   = 17;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'var_yhat_au' ;
  2 , 'name' , 'var_i_gap' ;
  3 , 'name' , 'var_pi_au_gap' ;
  4 , 'name' , 'var_u_gap' ;
  5 , 'name' , 'var_yhat_us' ;
  6 , 'name' , 'var_pi_us_gap' ;
  7 , 'name' , 'var_ibar' ;
  8 , 'name' , 'var_pibar_au' ;
  9 , 'name' , 'var_pibar_us' ;
  10 , 'name' , 'var_piQ' ;
  11 , 'name' , 'var_pi_m' ;
  12 , 'name' , 'var_dln_pcom' ;
  13 , 'name' , 'var_ib' ;
  14 , 'name' , 'var_rKB' ;
  15 , 'name' , 'eq_dln_ib_pac' ;
};
M_.mapping.yhat_au.eqidx = [1 2 3 4 13 15 19 ];
M_.mapping.pi_au_gap.eqidx = [1 2 3 13 19 ];
M_.mapping.i_gap.eqidx = [1 2 14 19 ];
M_.mapping.u_gap.eqidx = [4 13 19 ];
M_.mapping.yhat_us.eqidx = [1 5 6 19 ];
M_.mapping.pi_us_gap.eqidx = [6 19 ];
M_.mapping.ibar.eqidx = [7 19 ];
M_.mapping.pibar_au.eqidx = [3 8 19 ];
M_.mapping.pibar_us.eqidx = [9 19 ];
M_.mapping.piQ.eqidx = [3 10 19 ];
M_.mapping.pi_m.eqidx = [3 11 19 ];
M_.mapping.dln_pcom.eqidx = [3 12 19 ];
M_.mapping.ib_hat.eqidx = [13 15 19 ];
M_.mapping.rKB_hat.eqidx = [14 19 ];
M_.mapping.ln_ib_level.eqidx = [15 16 17 18 ];
M_.mapping.eps_q.eqidx = [1 ];
M_.mapping.eps_i.eqidx = [2 ];
M_.mapping.eps_pi.eqidx = [3 ];
M_.mapping.eps_q_us.eqidx = [5 ];
M_.mapping.eps_pi_us.eqidx = [6 ];
M_.mapping.eps_ibar.eqidx = [7 ];
M_.mapping.eps_pibar_au.eqidx = [8 ];
M_.mapping.eps_pibar_us.eqidx = [9 ];
M_.mapping.eps_u_gap.eqidx = [4 ];
M_.mapping.eps_piQ.eqidx = [10 ];
M_.mapping.eps_pi_m.eqidx = [11 ];
M_.mapping.eps_pcom.eqidx = [12 ];
M_.mapping.eps_var_ib.eqidx = [13 ];
M_.mapping.eps_var_rKB.eqidx = [14 ];
M_.mapping.eps_ib.eqidx = [15 ];
M_.mapping.pac_expectation_pac_ib.eqidx = [15 19 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = true;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 19;
M_.block_structure.block(1).mfs = 19;
M_.block_structure.block(1).equation = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 17 18 19 15 16];
M_.block_structure.block(1).variable = [ 1 3 2 4 5 6 7 8 9 10 11 12 13 14 17 18 19 16 15];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 24;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 1 3 2 4 5 6 7 8 9 10 11 12 13 14 17 18 19 16 15];
M_.block_structure.equation_reordered = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 17 18 19 15 16];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 5;
 2 1;
 2 2;
 2 3;
 3 1;
 3 2;
 3 8;
 3 10;
 3 11;
 3 12;
 4 1;
 4 4;
 5 5;
 6 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 1;
 13 2;
 13 4;
 13 13;
 14 3;
 14 14;
 15 13;
 15 15;
 16 15;
 17 16;
 18 17;
 19 1;
 19 2;
 19 3;
 19 4;
 19 5;
 19 6;
 19 7;
 19 8;
 19 9;
 19 10;
 19 11;
 19 12;
 19 13;
 19 14;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 2 3;
 3 2;
 4 4;
 5 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 13;
 14 14;
 15 1;
 15 16;
 15 17;
 15 18;
 15 19;
 16 15;
 16 16;
 17 17;
 18 18;
 19 19;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [1 3 2 4 5 6 7 8 9 10 11 12 13 14 17 16 15 ];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(19, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(15, 1);
M_.params = NaN(51, 1);
M_.endo_trends = struct('deflator', cell(19, 1), 'log_deflator', cell(19, 1), 'growth_factor', cell(19, 1), 'log_growth_factor', cell(19, 1));
M_.NNZDerivatives = [88; 0; -1; ];
M_.dynamic_g1_sparse_rowval = int32([1 2 3 4 13 19 1 2 3 13 19 1 2 14 19 4 13 19 1 5 6 19 6 19 7 19 3 8 19 9 19 3 10 19 3 11 19 3 12 19 13 15 19 14 19 15 16 17 18 1 15 3 2 4 5 6 7 8 9 10 11 12 13 14 16 15 16 15 17 15 18 15 19 1 2 3 5 6 7 8 9 4 10 11 12 13 14 15 ]);
M_.dynamic_g1_sparse_colval = int32([1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 4 4 4 5 5 5 5 6 6 7 7 8 8 8 9 9 10 10 10 11 11 11 12 12 12 13 13 13 14 14 15 15 16 17 20 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 35 36 36 37 37 38 38 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 ]);
M_.dynamic_g1_sparse_colptr = int32([1 7 12 16 19 23 25 27 30 32 35 38 41 44 46 48 49 50 50 50 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 68 70 72 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'yhat_au'; 
'i_gap'; 
'pi_au_gap'; 
'u_gap'; 
'yhat_us'; 
'pi_us_gap'; 
'ibar'; 
'pibar_au'; 
'pibar_us'; 
'piQ'; 
'pi_m'; 
'dln_pcom'; 
'ib_hat'; 
'rKB_hat'; 
'AUX_DIFF_172'; 
'AUX_DIFF_172'; 
'AUX_DIFF_LAG_175'; 
'AUX_DIFF_LAG_184'; 
'pac_expectation_pac_ib'; 
};
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 3;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 5];
M_.block_structure_stat.block(1).variable = [ 5];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 6];
M_.block_structure_stat.block(2).variable = [ 6];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 7];
M_.block_structure_stat.block(3).variable = [ 7];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 8];
M_.block_structure_stat.block(4).variable = [ 8];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 9];
M_.block_structure_stat.block(5).variable = [ 9];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 10];
M_.block_structure_stat.block(6).variable = [ 10];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 11];
M_.block_structure_stat.block(7).variable = [ 11];
M_.block_structure_stat.block(8).Simulation_Type = 3;
M_.block_structure_stat.block(8).endo_nbr = 1;
M_.block_structure_stat.block(8).mfs = 1;
M_.block_structure_stat.block(8).equation = [ 12];
M_.block_structure_stat.block(8).variable = [ 12];
M_.block_structure_stat.block(9).Simulation_Type = 1;
M_.block_structure_stat.block(9).endo_nbr = 3;
M_.block_structure_stat.block(9).mfs = 3;
M_.block_structure_stat.block(9).equation = [ 16 17 18];
M_.block_structure_stat.block(9).variable = [ 16 17 18];
M_.block_structure_stat.block(10).Simulation_Type = 6;
M_.block_structure_stat.block(10).endo_nbr = 3;
M_.block_structure_stat.block(10).mfs = 3;
M_.block_structure_stat.block(10).equation = [ 3 2 1];
M_.block_structure_stat.block(10).variable = [ 1 3 2];
M_.block_structure_stat.block(11).Simulation_Type = 3;
M_.block_structure_stat.block(11).endo_nbr = 1;
M_.block_structure_stat.block(11).mfs = 1;
M_.block_structure_stat.block(11).equation = [ 4];
M_.block_structure_stat.block(11).variable = [ 4];
M_.block_structure_stat.block(12).Simulation_Type = 3;
M_.block_structure_stat.block(12).endo_nbr = 1;
M_.block_structure_stat.block(12).mfs = 1;
M_.block_structure_stat.block(12).equation = [ 14];
M_.block_structure_stat.block(12).variable = [ 14];
M_.block_structure_stat.block(13).Simulation_Type = 3;
M_.block_structure_stat.block(13).endo_nbr = 1;
M_.block_structure_stat.block(13).mfs = 1;
M_.block_structure_stat.block(13).equation = [ 13];
M_.block_structure_stat.block(13).variable = [ 13];
M_.block_structure_stat.block(14).Simulation_Type = 1;
M_.block_structure_stat.block(14).endo_nbr = 1;
M_.block_structure_stat.block(14).mfs = 1;
M_.block_structure_stat.block(14).equation = [ 19];
M_.block_structure_stat.block(14).variable = [ 19];
M_.block_structure_stat.block(15).Simulation_Type = 3;
M_.block_structure_stat.block(15).endo_nbr = 1;
M_.block_structure_stat.block(15).mfs = 1;
M_.block_structure_stat.block(15).equation = [ 15];
M_.block_structure_stat.block(15).variable = [ 15];
M_.block_structure_stat.variable_reordered = [ 5 6 7 8 9 10 11 12 16 17 18 1 3 2 4 14 13 19 15];
M_.block_structure_stat.equation_reordered = [ 5 6 7 8 9 10 11 12 16 17 18 3 2 1 4 14 13 19 15];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 5;
 2 1;
 2 2;
 2 3;
 3 1;
 3 2;
 3 8;
 3 10;
 3 11;
 3 12;
 4 1;
 4 4;
 5 5;
 6 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 1;
 13 2;
 13 4;
 13 13;
 14 3;
 14 14;
 15 1;
 15 13;
 15 15;
 15 16;
 15 17;
 15 18;
 15 19;
 16 16;
 17 16;
 17 17;
 18 17;
 18 18;
 19 1;
 19 2;
 19 3;
 19 4;
 19 5;
 19 6;
 19 7;
 19 8;
 19 9;
 19 10;
 19 11;
 19 12;
 19 13;
 19 14;
 19 19;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(8).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(9).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(9).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(9).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(10).g1_sparse_rowval = int32([1 2 3 2 3 1 2 3 ]);
M_.block_structure_stat.block(10).g1_sparse_colval = int32([1 1 1 2 2 3 3 3 ]);
M_.block_structure_stat.block(10).g1_sparse_colptr = int32([1 4 6 9 ]);
M_.block_structure_stat.block(11).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(12).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(13).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(13).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(13).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(14).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(14).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(14).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(15).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(15).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(15).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 2 3 4 13 15 19 1 2 3 13 19 1 2 14 19 4 13 19 1 5 6 19 6 19 7 19 3 8 19 9 19 3 10 19 3 11 19 3 12 19 13 15 19 14 19 15 15 16 17 15 17 18 15 18 15 19 ]);
M_.static_g1_sparse_colval = int32([1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 4 4 4 5 5 5 5 6 6 7 7 8 8 8 9 9 10 10 10 11 11 11 12 12 12 13 13 13 14 14 15 16 16 16 17 17 17 18 18 19 19 ]);
M_.static_g1_sparse_colptr = int32([1 8 13 17 20 24 26 28 31 33 36 39 42 45 47 48 51 54 56 58 ]);
M_.params(1) = 0.1989;
delta = M_.params(1);
M_.params(2) = 0.6959;
lambda_q = M_.params(2);
M_.params(3) = 0.0648;
sigma_q = M_.params(3);
M_.params(4) = 0.9576;
lambda_i = M_.params(4);
M_.params(5) = 0.3001;
alpha_i = M_.params(5);
M_.params(6) = 0.0837;
beta_i = M_.params(6);
M_.params(7) = 0.2902;
lambda_pi = M_.params(7);
M_.params(8) = 0.0374;
kappa_pi = M_.params(8);
M_.params(9) = 0.8057;
lambda_q_us = M_.params(9);
M_.params(10) = 0.6529;
lambda_pi_us = M_.params(10);
M_.params(11) = 0.0131;
kappa_pi_us = M_.params(11);
M_.params(12) = 0.985;
lambda_ibar = M_.params(12);
M_.params(13) = 0.93;
lambda_pibar = M_.params(13);
M_.params(14) = 0.93;
lambda_pibar_us = M_.params(14);
M_.params(15) = 0.94;
rho_u_gap = M_.params(15);
M_.params(16) = (-0.33);
okun_coeff = M_.params(16);
M_.params(17) = 0.17;
alpha_pc = M_.params(17);
M_.params(18) = 0.10;
beta_pc_m = M_.params(18);
M_.params(19) = 0.03;
gamma_oil = M_.params(19);
M_.params(20) = 1.0491;
i_ss = M_.params(20);
M_.params(21) = 0.625;
pi_ss_au = M_.params(21);
M_.params(22) = 0.5;
pi_ss_us = M_.params(22);
M_.params(23) = 0.85;
rho_piQ = M_.params(23);
M_.params(24) = 0.7;
rho_pi_m = M_.params(24);
M_.params(25) = 0.42;
rho_pcom = M_.params(25);
M_.params(26) = 0.6;
rho_ib_aux = M_.params(26);
M_.params(27) = 0.15;
a_ib_y = M_.params(27);
M_.params(28) = 0.04;
a_ib_pi = M_.params(28);
M_.params(29) = (-0.02);
a_ib_u = M_.params(29);
M_.params(30) = 0.55;
rho_rKB_aux = M_.params(30);
M_.params(31) = 0.24;
a_rKB_i = M_.params(31);
M_.params(32) = 0.0180;
b0_ib = M_.params(32);
M_.params(33) = 0.0818;
b1_ib = M_.params(33);
M_.params(34) = 0.0;
b2_ib = M_.params(34);
M_.params(35) = 0.3144;
b3_ib = M_.params(35);
M_.params(36) = 0.98;
beta_pac = M_.params(36);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.527)^2;
M_.Sigma_e(2, 2) = (0.110)^2;
M_.Sigma_e(3, 3) = (0.590)^2;
M_.Sigma_e(4, 4) = (1.138)^2;
M_.Sigma_e(5, 5) = (0.319)^2;
M_.Sigma_e(6, 6) = (0.01)^2;
M_.Sigma_e(7, 7) = (0.01)^2;
M_.Sigma_e(8, 8) = (0.01)^2;
M_.Sigma_e(9, 9) = (0.05)^2;
M_.Sigma_e(10, 10) = (0.571)^2;
M_.Sigma_e(11, 11) = (0.5)^2;
M_.Sigma_e(12, 12) = (3.0)^2;
M_.Sigma_e(13, 13) = (0.01)^2;
M_.Sigma_e(14, 14) = (0.01)^2;
M_.Sigma_e(15, 15) = (2.78)^2;
pac.initialize('pac_ib');
pac.update.expectation('pac_ib');
pac.print('pac_ib', 'eq_dln_ib_pac');


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_business_inv_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
