function [AR, A0, A0star] = trend_component_ar_a0(model_name, params)
%function [AR, A0, A0star] = trend_component_ar_a0(model_name, params)
% File automatically generated by the Dynare preprocessor

if strcmp(model_name, 'c_tcm')
    % AR
    AR = zeros(1, 1, 1);
    AR(1, 1, 1) = params(43);

    % A0
    A0 = zeros(1, 1);

    % A0star
    A0star = zeros(1, 1);
    A0star(1, 1) = (-params(42));
    return
end

if strcmp(model_name, 'esat_tcm')
    % AR
    AR = zeros(1, 1, 1);
    AR(1, 1, 1) = params(20);

    % A0
    A0 = zeros(1, 1);

    % A0star
    A0star = zeros(1, 1);
    A0star(1, 1) = (-params(19));
    return
end

if strcmp(model_name, 'ib_tcm')
    % AR
    AR = zeros(1, 1, 1);
    AR(1, 1, 1) = params(50);

    % A0
    A0 = zeros(1, 1);

    % A0star
    A0star = zeros(1, 1);
    A0star(1, 1) = (-params(49));
    return
end

if strcmp(model_name, 'ih_tcm')
    % AR
    AR = zeros(1, 1, 1);
    AR(1, 1, 1) = params(59);

    % A0
    A0 = zeros(1, 1);

    % A0star
    A0star = zeros(1, 1);
    A0star(1, 1) = (-params(58));
    return
end

if strcmp(model_name, 'n_tcm')
    % AR
    AR = zeros(1, 1, 1);
    AR(1, 1, 1) = params(35);

    % A0
    A0 = zeros(1, 1);

    % A0star
    A0star = zeros(1, 1);
    A0star(1, 1) = (-params(34));
    return
end

error([model_name ' is not a valid trend_component_model name'])
end
