function [ar, a0, constants] = varmatrices(model_name, params, reducedform)
% File automatically generated by the Dynare preprocessor

if nargin<3
    reducedform = false;
end

if strcmp(model_name, 'esat_enriched')
    ar = zeros(8, 8, 1);
    ar(1,1,1) = params(2);
    ar(1,2,1) = (-params(3));
    ar(1,3,1) = params(3);
    ar(2,1,1) = (1-params(4))*params(6);
    ar(2,2,1) = params(4);
    ar(2,3,1) = (1-params(4))*params(5);
    ar(3,1,1) = params(8);
    ar(3,3,1) = params(7);
    ar(4,1,1) = params(153);
    ar(4,2,1) = params(154);
    ar(4,3,1) = params(155);
    ar(4,4,1) = params(152);
    ar(5,1,1) = params(157);
    ar(5,2,1) = params(158);
    ar(5,3,1) = params(159);
    ar(5,5,1) = params(156);
    ar(6,1,1) = params(161);
    ar(6,2,1) = params(162);
    ar(6,3,1) = params(163);
    ar(6,6,1) = params(160);
    ar(7,1,1) = params(165);
    ar(7,2,1) = params(166);
    ar(7,3,1) = params(167);
    ar(7,7,1) = params(164);
    ar(8,1,1) = params(169);
    ar(8,2,1) = params(170);
    ar(8,3,1) = params(171);
    ar(8,8,1) = params(168);
    if nargout>1
        a0 = eye(8);
        if reducedform
            for i=1:1
                ar(:,:,i) = a0\ar(:,:,i);
            end
            if nargout<3
                a0 = eye(8);
            end
        end
        if nargout>2
            constants = zeros(8,1);
        end
        if reducedform
            constants = a0\constants;
            a0 = eye(8);
        end
    end
    return
end

error('%s is not a valid var_model name', model_name)
