%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'aux_consumption';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(15,1);
M_.exo_names_tex = cell(15,1);
M_.exo_names_long = cell(15,1);
M_.exo_names(1) = {'eps_q'};
M_.exo_names_tex(1) = {'eps\_q'};
M_.exo_names_long(1) = {'eps_q'};
M_.exo_names(2) = {'eps_i'};
M_.exo_names_tex(2) = {'eps\_i'};
M_.exo_names_long(2) = {'eps_i'};
M_.exo_names(3) = {'eps_pi'};
M_.exo_names_tex(3) = {'eps\_pi'};
M_.exo_names_long(3) = {'eps_pi'};
M_.exo_names(4) = {'eps_q_us'};
M_.exo_names_tex(4) = {'eps\_q\_us'};
M_.exo_names_long(4) = {'eps_q_us'};
M_.exo_names(5) = {'eps_pi_us'};
M_.exo_names_tex(5) = {'eps\_pi\_us'};
M_.exo_names_long(5) = {'eps_pi_us'};
M_.exo_names(6) = {'eps_ibar'};
M_.exo_names_tex(6) = {'eps\_ibar'};
M_.exo_names_long(6) = {'eps_ibar'};
M_.exo_names(7) = {'eps_pibar_au'};
M_.exo_names_tex(7) = {'eps\_pibar\_au'};
M_.exo_names_long(7) = {'eps_pibar_au'};
M_.exo_names(8) = {'eps_pibar_us'};
M_.exo_names_tex(8) = {'eps\_pibar\_us'};
M_.exo_names_long(8) = {'eps_pibar_us'};
M_.exo_names(9) = {'eps_u_gap'};
M_.exo_names_tex(9) = {'eps\_u\_gap'};
M_.exo_names_long(9) = {'eps_u_gap'};
M_.exo_names(10) = {'eps_piQ'};
M_.exo_names_tex(10) = {'eps\_piQ'};
M_.exo_names_long(10) = {'eps_piQ'};
M_.exo_names(11) = {'eps_pi_m'};
M_.exo_names_tex(11) = {'eps\_pi\_m'};
M_.exo_names_long(11) = {'eps_pi_m'};
M_.exo_names(12) = {'eps_pcom'};
M_.exo_names_tex(12) = {'eps\_pcom'};
M_.exo_names_long(12) = {'eps_pcom'};
M_.exo_names(13) = {'eps_var_yh'};
M_.exo_names_tex(13) = {'eps\_var\_yh'};
M_.exo_names_long(13) = {'eps_var_yh'};
M_.exo_names(14) = {'eps_var_c'};
M_.exo_names_tex(14) = {'eps\_var\_c'};
M_.exo_names_long(14) = {'eps_var_c'};
M_.exo_names(15) = {'eps_c'};
M_.exo_names_tex(15) = {'eps\_c'};
M_.exo_names_long(15) = {'eps_c'};
M_.endo_names = cell(18,1);
M_.endo_names_tex = cell(18,1);
M_.endo_names_long = cell(18,1);
M_.endo_names(1) = {'yhat_au'};
M_.endo_names_tex(1) = {'yhat\_au'};
M_.endo_names_long(1) = {'yhat_au'};
M_.endo_names(2) = {'pi_au_gap'};
M_.endo_names_tex(2) = {'pi\_au\_gap'};
M_.endo_names_long(2) = {'pi_au_gap'};
M_.endo_names(3) = {'i_gap'};
M_.endo_names_tex(3) = {'i\_gap'};
M_.endo_names_long(3) = {'i_gap'};
M_.endo_names(4) = {'u_gap'};
M_.endo_names_tex(4) = {'u\_gap'};
M_.endo_names_long(4) = {'u_gap'};
M_.endo_names(5) = {'yhat_us'};
M_.endo_names_tex(5) = {'yhat\_us'};
M_.endo_names_long(5) = {'yhat_us'};
M_.endo_names(6) = {'pi_us_gap'};
M_.endo_names_tex(6) = {'pi\_us\_gap'};
M_.endo_names_long(6) = {'pi_us_gap'};
M_.endo_names(7) = {'ibar'};
M_.endo_names_tex(7) = {'ibar'};
M_.endo_names_long(7) = {'ibar'};
M_.endo_names(8) = {'pibar_au'};
M_.endo_names_tex(8) = {'pibar\_au'};
M_.endo_names_long(8) = {'pibar_au'};
M_.endo_names(9) = {'pibar_us'};
M_.endo_names_tex(9) = {'pibar\_us'};
M_.endo_names_long(9) = {'pibar_us'};
M_.endo_names(10) = {'piQ'};
M_.endo_names_tex(10) = {'piQ'};
M_.endo_names_long(10) = {'piQ'};
M_.endo_names(11) = {'pi_m'};
M_.endo_names_tex(11) = {'pi\_m'};
M_.endo_names_long(11) = {'pi_m'};
M_.endo_names(12) = {'dln_pcom'};
M_.endo_names_tex(12) = {'dln\_pcom'};
M_.endo_names_long(12) = {'dln_pcom'};
M_.endo_names(13) = {'yh_ratio_hat'};
M_.endo_names_tex(13) = {'yh\_ratio\_hat'};
M_.endo_names_long(13) = {'yh_ratio_hat'};
M_.endo_names(14) = {'c_hat'};
M_.endo_names_tex(14) = {'c\_hat'};
M_.endo_names_long(14) = {'c_hat'};
M_.endo_names(15) = {'ln_c_level'};
M_.endo_names_tex(15) = {'ln\_c\_level'};
M_.endo_names_long(15) = {'ln_c_level'};
M_.endo_names(16) = {'AUX_DIFF_181'};
M_.endo_names_tex(16) = {'AUX\_DIFF\_181'};
M_.endo_names_long(16) = {'AUX_DIFF_181'};
M_.endo_names(17) = {'AUX_DIFF_LAG_184'};
M_.endo_names_tex(17) = {'AUX\_DIFF\_LAG\_184'};
M_.endo_names_long(17) = {'AUX_DIFF_LAG_184'};
M_.endo_names(18) = {'pac_expectation_pac_c'};
M_.endo_names_tex(18) = {'pac\_expectation\_pac\_c'};
M_.endo_names_long(18) = {'pac_expectation_pac_c'};
M_.endo_partitions = struct();
M_.param_names = cell(54,1);
M_.param_names_tex = cell(54,1);
M_.param_names_long = cell(54,1);
M_.param_names(1) = {'delta'};
M_.param_names_tex(1) = {'delta'};
M_.param_names_long(1) = {'delta'};
M_.param_names(2) = {'lambda_q'};
M_.param_names_tex(2) = {'lambda\_q'};
M_.param_names_long(2) = {'lambda_q'};
M_.param_names(3) = {'sigma_q'};
M_.param_names_tex(3) = {'sigma\_q'};
M_.param_names_long(3) = {'sigma_q'};
M_.param_names(4) = {'lambda_i'};
M_.param_names_tex(4) = {'lambda\_i'};
M_.param_names_long(4) = {'lambda_i'};
M_.param_names(5) = {'alpha_i'};
M_.param_names_tex(5) = {'alpha\_i'};
M_.param_names_long(5) = {'alpha_i'};
M_.param_names(6) = {'beta_i'};
M_.param_names_tex(6) = {'beta\_i'};
M_.param_names_long(6) = {'beta_i'};
M_.param_names(7) = {'lambda_pi'};
M_.param_names_tex(7) = {'lambda\_pi'};
M_.param_names_long(7) = {'lambda_pi'};
M_.param_names(8) = {'kappa_pi'};
M_.param_names_tex(8) = {'kappa\_pi'};
M_.param_names_long(8) = {'kappa_pi'};
M_.param_names(9) = {'lambda_q_us'};
M_.param_names_tex(9) = {'lambda\_q\_us'};
M_.param_names_long(9) = {'lambda_q_us'};
M_.param_names(10) = {'lambda_pi_us'};
M_.param_names_tex(10) = {'lambda\_pi\_us'};
M_.param_names_long(10) = {'lambda_pi_us'};
M_.param_names(11) = {'kappa_pi_us'};
M_.param_names_tex(11) = {'kappa\_pi\_us'};
M_.param_names_long(11) = {'kappa_pi_us'};
M_.param_names(12) = {'lambda_ibar'};
M_.param_names_tex(12) = {'lambda\_ibar'};
M_.param_names_long(12) = {'lambda_ibar'};
M_.param_names(13) = {'lambda_pibar'};
M_.param_names_tex(13) = {'lambda\_pibar'};
M_.param_names_long(13) = {'lambda_pibar'};
M_.param_names(14) = {'lambda_pibar_us'};
M_.param_names_tex(14) = {'lambda\_pibar\_us'};
M_.param_names_long(14) = {'lambda_pibar_us'};
M_.param_names(15) = {'rho_u_gap'};
M_.param_names_tex(15) = {'rho\_u\_gap'};
M_.param_names_long(15) = {'rho_u_gap'};
M_.param_names(16) = {'okun_coeff'};
M_.param_names_tex(16) = {'okun\_coeff'};
M_.param_names_long(16) = {'okun_coeff'};
M_.param_names(17) = {'alpha_pc'};
M_.param_names_tex(17) = {'alpha\_pc'};
M_.param_names_long(17) = {'alpha_pc'};
M_.param_names(18) = {'beta_pc_m'};
M_.param_names_tex(18) = {'beta\_pc\_m'};
M_.param_names_long(18) = {'beta_pc_m'};
M_.param_names(19) = {'gamma_oil'};
M_.param_names_tex(19) = {'gamma\_oil'};
M_.param_names_long(19) = {'gamma_oil'};
M_.param_names(20) = {'i_ss'};
M_.param_names_tex(20) = {'i\_ss'};
M_.param_names_long(20) = {'i_ss'};
M_.param_names(21) = {'pi_ss_au'};
M_.param_names_tex(21) = {'pi\_ss\_au'};
M_.param_names_long(21) = {'pi_ss_au'};
M_.param_names(22) = {'pi_ss_us'};
M_.param_names_tex(22) = {'pi\_ss\_us'};
M_.param_names_long(22) = {'pi_ss_us'};
M_.param_names(23) = {'rho_piQ'};
M_.param_names_tex(23) = {'rho\_piQ'};
M_.param_names_long(23) = {'rho_piQ'};
M_.param_names(24) = {'rho_pi_m'};
M_.param_names_tex(24) = {'rho\_pi\_m'};
M_.param_names_long(24) = {'rho_pi_m'};
M_.param_names(25) = {'rho_pcom'};
M_.param_names_tex(25) = {'rho\_pcom'};
M_.param_names_long(25) = {'rho_pcom'};
M_.param_names(26) = {'rho_yh_aux'};
M_.param_names_tex(26) = {'rho\_yh\_aux'};
M_.param_names_long(26) = {'rho_yh_aux'};
M_.param_names(27) = {'a_yh_y'};
M_.param_names_tex(27) = {'a\_yh\_y'};
M_.param_names_long(27) = {'a_yh_y'};
M_.param_names(28) = {'a_yh_u'};
M_.param_names_tex(28) = {'a\_yh\_u'};
M_.param_names_long(28) = {'a_yh_u'};
M_.param_names(29) = {'rho_c_aux'};
M_.param_names_tex(29) = {'rho\_c\_aux'};
M_.param_names_long(29) = {'rho_c_aux'};
M_.param_names(30) = {'a_c_y'};
M_.param_names_tex(30) = {'a\_c\_y'};
M_.param_names_long(30) = {'a_c_y'};
M_.param_names(31) = {'a_c_i'};
M_.param_names_tex(31) = {'a\_c\_i'};
M_.param_names_long(31) = {'a_c_i'};
M_.param_names(32) = {'a_c_pi'};
M_.param_names_tex(32) = {'a\_c\_pi'};
M_.param_names_long(32) = {'a_c_pi'};
M_.param_names(33) = {'a_c_u'};
M_.param_names_tex(33) = {'a\_c\_u'};
M_.param_names_long(33) = {'a_c_u'};
M_.param_names(34) = {'a_c_yh'};
M_.param_names_tex(34) = {'a\_c\_yh'};
M_.param_names_long(34) = {'a_c_yh'};
M_.param_names(35) = {'b0_c'};
M_.param_names_tex(35) = {'b0\_c'};
M_.param_names_long(35) = {'b0_c'};
M_.param_names(36) = {'b1_c'};
M_.param_names_tex(36) = {'b1\_c'};
M_.param_names_long(36) = {'b1_c'};
M_.param_names(37) = {'b2_c'};
M_.param_names_tex(37) = {'b2\_c'};
M_.param_names_long(37) = {'b2_c'};
M_.param_names(38) = {'b3_c'};
M_.param_names_tex(38) = {'b3\_c'};
M_.param_names_long(38) = {'b3_c'};
M_.param_names(39) = {'beta_pac'};
M_.param_names_tex(39) = {'beta\_pac'};
M_.param_names_long(39) = {'beta_pac'};
M_.param_names(40) = {'h_pac_c_constant'};
M_.param_names_tex(40) = {'h\_pac\_c\_constant'};
M_.param_names_long(40) = {'h_pac_c_constant'};
M_.param_names(41) = {'h_pac_c_var_yhat_au_lag_1'};
M_.param_names_tex(41) = {'h\_pac\_c\_var\_yhat\_au\_lag\_1'};
M_.param_names_long(41) = {'h_pac_c_var_yhat_au_lag_1'};
M_.param_names(42) = {'h_pac_c_var_i_gap_lag_1'};
M_.param_names_tex(42) = {'h\_pac\_c\_var\_i\_gap\_lag\_1'};
M_.param_names_long(42) = {'h_pac_c_var_i_gap_lag_1'};
M_.param_names(43) = {'h_pac_c_var_pi_au_gap_lag_1'};
M_.param_names_tex(43) = {'h\_pac\_c\_var\_pi\_au\_gap\_lag\_1'};
M_.param_names_long(43) = {'h_pac_c_var_pi_au_gap_lag_1'};
M_.param_names(44) = {'h_pac_c_var_u_gap_lag_1'};
M_.param_names_tex(44) = {'h\_pac\_c\_var\_u\_gap\_lag\_1'};
M_.param_names_long(44) = {'h_pac_c_var_u_gap_lag_1'};
M_.param_names(45) = {'h_pac_c_var_yhat_us_lag_1'};
M_.param_names_tex(45) = {'h\_pac\_c\_var\_yhat\_us\_lag\_1'};
M_.param_names_long(45) = {'h_pac_c_var_yhat_us_lag_1'};
M_.param_names(46) = {'h_pac_c_var_pi_us_gap_lag_1'};
M_.param_names_tex(46) = {'h\_pac\_c\_var\_pi\_us\_gap\_lag\_1'};
M_.param_names_long(46) = {'h_pac_c_var_pi_us_gap_lag_1'};
M_.param_names(47) = {'h_pac_c_var_ibar_lag_1'};
M_.param_names_tex(47) = {'h\_pac\_c\_var\_ibar\_lag\_1'};
M_.param_names_long(47) = {'h_pac_c_var_ibar_lag_1'};
M_.param_names(48) = {'h_pac_c_var_pibar_au_lag_1'};
M_.param_names_tex(48) = {'h\_pac\_c\_var\_pibar\_au\_lag\_1'};
M_.param_names_long(48) = {'h_pac_c_var_pibar_au_lag_1'};
M_.param_names(49) = {'h_pac_c_var_pibar_us_lag_1'};
M_.param_names_tex(49) = {'h\_pac\_c\_var\_pibar\_us\_lag\_1'};
M_.param_names_long(49) = {'h_pac_c_var_pibar_us_lag_1'};
M_.param_names(50) = {'h_pac_c_var_piQ_lag_1'};
M_.param_names_tex(50) = {'h\_pac\_c\_var\_piQ\_lag\_1'};
M_.param_names_long(50) = {'h_pac_c_var_piQ_lag_1'};
M_.param_names(51) = {'h_pac_c_var_pi_m_lag_1'};
M_.param_names_tex(51) = {'h\_pac\_c\_var\_pi\_m\_lag\_1'};
M_.param_names_long(51) = {'h_pac_c_var_pi_m_lag_1'};
M_.param_names(52) = {'h_pac_c_var_dln_pcom_lag_1'};
M_.param_names_tex(52) = {'h\_pac\_c\_var\_dln\_pcom\_lag\_1'};
M_.param_names_long(52) = {'h_pac_c_var_dln_pcom_lag_1'};
M_.param_names(53) = {'h_pac_c_var_yh_ratio_hat_lag_1'};
M_.param_names_tex(53) = {'h\_pac\_c\_var\_yh\_ratio\_hat\_lag\_1'};
M_.param_names_long(53) = {'h_pac_c_var_yh_ratio_hat_lag_1'};
M_.param_names(54) = {'h_pac_c_var_c_hat_lag_1'};
M_.param_names_tex(54) = {'h\_pac\_c\_var\_c\_hat\_lag\_1'};
M_.param_names_long(54) = {'h_pac_c_var_c_hat_lag_1'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 15;
M_.endo_nbr = 18;
M_.param_nbr = 54;
M_.orig_endo_nbr = 15;
M_.aux_vars(1).endo_index = 16;
M_.aux_vars(1).type = 8;
M_.aux_vars(1).orig_index = 15;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'diff(ln_c_level)';
M_.aux_vars(2).endo_index = 17;
M_.aux_vars(2).type = 9;
M_.aux_vars(2).orig_index = 16;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'diff(ln_c_level(-1))';
M_.aux_vars(3).endo_index = 18;
M_.aux_vars(3).type = 12;
M_.aux_vars(3).orig_expr = 'h_pac_c_constant+yhat_au(-1)*h_pac_c_var_yhat_au_lag_1+i_gap(-1)*h_pac_c_var_i_gap_lag_1+pi_au_gap(-1)*h_pac_c_var_pi_au_gap_lag_1+u_gap(-1)*h_pac_c_var_u_gap_lag_1+yhat_us(-1)*h_pac_c_var_yhat_us_lag_1+pi_us_gap(-1)*h_pac_c_var_pi_us_gap_lag_1+ibar(-1)*h_pac_c_var_ibar_lag_1+pibar_au(-1)*h_pac_c_var_pibar_au_lag_1+pibar_us(-1)*h_pac_c_var_pibar_us_lag_1+piQ(-1)*h_pac_c_var_piQ_lag_1+pi_m(-1)*h_pac_c_var_pi_m_lag_1+dln_pcom(-1)*h_pac_c_var_dln_pcom_lag_1+yh_ratio_hat(-1)*h_pac_c_var_yh_ratio_hat_lag_1+c_hat(-1)*h_pac_c_var_c_hat_lag_1';
M_.var.esat_consumption.model_name = 'esat_consumption';
M_.var.esat_consumption.structural = false;
M_.var.esat_consumption.eqtags = {'var_yhat_au'; 'var_i_gap'; 'var_pi_au_gap'; 'var_u_gap'; 'var_yhat_us'; 'var_pi_us_gap'; 'var_ibar'; 'var_pibar_au'; 'var_pibar_us'; 'var_piQ'; 'var_pi_m'; 'var_dln_pcom'; 'var_yh'; 'var_c'; };
M_.var.esat_consumption.eqn = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 ];
M_.var.esat_consumption.lhs = [1 3 2 4 5 6 7 8 9 10 11 12 13 14 ];
M_.var.esat_consumption.max_lag = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 ];
M_.var.esat_consumption.diff = [false false false false false false false false false false false false false false ];
M_.var.esat_consumption.nonstationary = M_.var.esat_consumption.diff;
M_.var.esat_consumption.orig_diff_var = [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{1}.var = [1 2 3 5 ];
M_.var.esat_consumption.rhs.vars_at_eq{1}.lag = [-1 -1 -1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{2}.var = [1 2 3 ];
M_.var.esat_consumption.rhs.vars_at_eq{2}.lag = [-1 -1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{3}.var = [1 2 8 10 11 12 ];
M_.var.esat_consumption.rhs.vars_at_eq{3}.lag = [-1 -1 -1 -1 -1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{4}.var = [1 4 ];
M_.var.esat_consumption.rhs.vars_at_eq{4}.lag = [-1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{5}.var = [5 ];
M_.var.esat_consumption.rhs.vars_at_eq{5}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{6}.var = [5 6 ];
M_.var.esat_consumption.rhs.vars_at_eq{6}.lag = [-1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{7}.var = [7 ];
M_.var.esat_consumption.rhs.vars_at_eq{7}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{8}.var = [8 ];
M_.var.esat_consumption.rhs.vars_at_eq{8}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{9}.var = [9 ];
M_.var.esat_consumption.rhs.vars_at_eq{9}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{10}.var = [10 ];
M_.var.esat_consumption.rhs.vars_at_eq{10}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{11}.var = [11 ];
M_.var.esat_consumption.rhs.vars_at_eq{11}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{12}.var = [12 ];
M_.var.esat_consumption.rhs.vars_at_eq{12}.lag = [-1 ];
M_.var.esat_consumption.rhs.vars_at_eq{13}.var = [1 4 13 ];
M_.var.esat_consumption.rhs.vars_at_eq{13}.lag = [-1 -1 -1 ];
M_.var.esat_consumption.rhs.vars_at_eq{14}.var = [1 2 3 4 13 14 ];
M_.var.esat_consumption.rhs.vars_at_eq{14}.lag = [-1 -1 -1 -1 -1 -1 ];
M_.pac.pac_c.auxiliary_model_name = 'esat_consumption';
M_.pac.pac_c.discount_index = 39;
M_.pac.pac_c.h_param_indices = [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 ];
M_.pac.pac_c.aux_id = 18;
M_.pac.pac_c.eq_name = 'eq_dln_c_pac';
M_.pac.pac_c.auxiliary_model_type = 'var';
M_.pac.pac_c.kind = '';
M_.pac.pac_c.lhs_var = 16;
M_.pac.pac_c.ec.params = 35;
M_.pac.pac_c.ec.vars = [14 15 ];
M_.pac.pac_c.ec.istarget = [true false ];
M_.pac.pac_c.ec.scale = [1 -1 ];
M_.pac.pac_c.ec.isendo = [true true ];
M_.pac.pac_c.ar.params = [36 ];
M_.pac.pac_c.ar.vars = [17 ];
M_.pac.pac_c.ar.lags = [0 ];
M_.pac.pac_c.max_lag = 1;
M_.pac.pac_c.additive.params = [NaN 38 37 ];
M_.pac.pac_c.additive.vars = [15 1 3 ];
M_.pac.pac_c.additive.isendo = [false true true ];
M_.pac.pac_c.additive.lags = [0 0 -1 ];
M_.pac.pac_c.additive.scaling_factor = [1 1 1 ];
M_.Sigma_e = zeros(15, 15);
M_.Correlation_matrix = eye(15, 15);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 18;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 0;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 0;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 1 17;
 2 18;
 3 19;
 4 20;
 5 21;
 6 22;
 7 23;
 8 24;
 9 25;
 10 26;
 11 27;
 12 28;
 13 29;
 14 30;
 15 31;
 16 32;
 0 33;
 0 34;]';
M_.nstatic = 2;
M_.nfwrd   = 0;
M_.npred   = 16;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 16;
M_.ndynamic   = 16;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'var_yhat_au' ;
  2 , 'name' , 'var_i_gap' ;
  3 , 'name' , 'var_pi_au_gap' ;
  4 , 'name' , 'var_u_gap' ;
  5 , 'name' , 'var_yhat_us' ;
  6 , 'name' , 'var_pi_us_gap' ;
  7 , 'name' , 'var_ibar' ;
  8 , 'name' , 'var_pibar_au' ;
  9 , 'name' , 'var_pibar_us' ;
  10 , 'name' , 'var_piQ' ;
  11 , 'name' , 'var_pi_m' ;
  12 , 'name' , 'var_dln_pcom' ;
  13 , 'name' , 'var_yh' ;
  14 , 'name' , 'var_c' ;
  15 , 'name' , 'eq_dln_c_pac' ;
};
M_.mapping.yhat_au.eqidx = [1 2 3 4 13 14 15 18 ];
M_.mapping.pi_au_gap.eqidx = [1 2 3 14 18 ];
M_.mapping.i_gap.eqidx = [1 2 14 15 18 ];
M_.mapping.u_gap.eqidx = [4 13 14 18 ];
M_.mapping.yhat_us.eqidx = [1 5 6 18 ];
M_.mapping.pi_us_gap.eqidx = [6 18 ];
M_.mapping.ibar.eqidx = [7 18 ];
M_.mapping.pibar_au.eqidx = [3 8 18 ];
M_.mapping.pibar_us.eqidx = [9 18 ];
M_.mapping.piQ.eqidx = [3 10 18 ];
M_.mapping.pi_m.eqidx = [3 11 18 ];
M_.mapping.dln_pcom.eqidx = [3 12 18 ];
M_.mapping.yh_ratio_hat.eqidx = [13 14 18 ];
M_.mapping.c_hat.eqidx = [14 15 18 ];
M_.mapping.ln_c_level.eqidx = [15 16 17 ];
M_.mapping.eps_q.eqidx = [1 ];
M_.mapping.eps_i.eqidx = [2 ];
M_.mapping.eps_pi.eqidx = [3 ];
M_.mapping.eps_q_us.eqidx = [5 ];
M_.mapping.eps_pi_us.eqidx = [6 ];
M_.mapping.eps_ibar.eqidx = [7 ];
M_.mapping.eps_pibar_au.eqidx = [8 ];
M_.mapping.eps_pibar_us.eqidx = [9 ];
M_.mapping.eps_u_gap.eqidx = [4 ];
M_.mapping.eps_piQ.eqidx = [10 ];
M_.mapping.eps_pi_m.eqidx = [11 ];
M_.mapping.eps_pcom.eqidx = [12 ];
M_.mapping.eps_var_yh.eqidx = [13 ];
M_.mapping.eps_var_c.eqidx = [14 ];
M_.mapping.eps_c.eqidx = [15 ];
M_.mapping.pac_expectation_pac_c.eqidx = [15 18 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = true;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 18;
M_.block_structure.block(1).mfs = 18;
M_.block_structure.block(1).equation = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 17 18 15 16];
M_.block_structure.block(1).variable = [ 1 3 2 4 5 6 7 8 9 10 11 12 13 14 17 18 16 15];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 22;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 1 3 2 4 5 6 7 8 9 10 11 12 13 14 17 18 16 15];
M_.block_structure.equation_reordered = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 17 18 15 16];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 5;
 2 1;
 2 2;
 2 3;
 3 1;
 3 2;
 3 8;
 3 10;
 3 11;
 3 12;
 4 1;
 4 4;
 5 5;
 6 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 1;
 13 4;
 13 13;
 14 1;
 14 2;
 14 3;
 14 4;
 14 13;
 14 14;
 15 3;
 15 14;
 15 15;
 16 15;
 17 16;
 18 1;
 18 2;
 18 3;
 18 4;
 18 5;
 18 6;
 18 7;
 18 8;
 18 9;
 18 10;
 18 11;
 18 12;
 18 13;
 18 14;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 2 3;
 3 2;
 4 4;
 5 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 13;
 14 14;
 15 1;
 15 16;
 15 17;
 15 18;
 16 15;
 16 16;
 17 17;
 18 18;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [1 3 2 4 5 6 7 8 9 10 11 12 13 14 16 15 ];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(18, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(15, 1);
M_.params = NaN(54, 1);
M_.endo_trends = struct('deflator', cell(18, 1), 'log_deflator', cell(18, 1), 'growth_factor', cell(18, 1), 'log_growth_factor', cell(18, 1));
M_.NNZDerivatives = [89; 0; -1; ];
M_.dynamic_g1_sparse_rowval = int32([1 2 3 4 13 14 18 1 2 3 14 18 1 2 14 15 18 4 13 14 18 1 5 6 18 6 18 7 18 3 8 18 9 18 3 10 18 3 11 18 3 12 18 13 14 18 14 15 18 15 16 17 1 15 3 2 4 5 6 7 8 9 10 11 12 13 14 16 15 16 15 17 15 18 1 2 3 5 6 7 8 9 4 10 11 12 13 14 15 ]);
M_.dynamic_g1_sparse_colval = int32([1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 5 5 5 5 6 6 7 7 8 8 8 9 9 10 10 10 11 11 11 12 12 12 13 13 13 14 14 14 15 15 16 19 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 34 35 35 36 36 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 ]);
M_.dynamic_g1_sparse_colptr = int32([1 8 13 18 22 26 28 30 33 35 38 41 44 47 50 52 53 53 53 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 71 73 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'yhat_au'; 
'i_gap'; 
'pi_au_gap'; 
'u_gap'; 
'yhat_us'; 
'pi_us_gap'; 
'ibar'; 
'pibar_au'; 
'pibar_us'; 
'piQ'; 
'pi_m'; 
'dln_pcom'; 
'yh_ratio_hat'; 
'c_hat'; 
'AUX_DIFF_181'; 
'AUX_DIFF_181'; 
'AUX_DIFF_LAG_184'; 
'pac_expectation_pac_c'; 
};
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 3;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 5];
M_.block_structure_stat.block(1).variable = [ 5];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 6];
M_.block_structure_stat.block(2).variable = [ 6];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 7];
M_.block_structure_stat.block(3).variable = [ 7];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 8];
M_.block_structure_stat.block(4).variable = [ 8];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 9];
M_.block_structure_stat.block(5).variable = [ 9];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 10];
M_.block_structure_stat.block(6).variable = [ 10];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 11];
M_.block_structure_stat.block(7).variable = [ 11];
M_.block_structure_stat.block(8).Simulation_Type = 3;
M_.block_structure_stat.block(8).endo_nbr = 1;
M_.block_structure_stat.block(8).mfs = 1;
M_.block_structure_stat.block(8).equation = [ 12];
M_.block_structure_stat.block(8).variable = [ 12];
M_.block_structure_stat.block(9).Simulation_Type = 1;
M_.block_structure_stat.block(9).endo_nbr = 2;
M_.block_structure_stat.block(9).mfs = 2;
M_.block_structure_stat.block(9).equation = [ 16 17];
M_.block_structure_stat.block(9).variable = [ 16 17];
M_.block_structure_stat.block(10).Simulation_Type = 6;
M_.block_structure_stat.block(10).endo_nbr = 3;
M_.block_structure_stat.block(10).mfs = 3;
M_.block_structure_stat.block(10).equation = [ 3 1 2];
M_.block_structure_stat.block(10).variable = [ 2 1 3];
M_.block_structure_stat.block(11).Simulation_Type = 3;
M_.block_structure_stat.block(11).endo_nbr = 1;
M_.block_structure_stat.block(11).mfs = 1;
M_.block_structure_stat.block(11).equation = [ 4];
M_.block_structure_stat.block(11).variable = [ 4];
M_.block_structure_stat.block(12).Simulation_Type = 3;
M_.block_structure_stat.block(12).endo_nbr = 1;
M_.block_structure_stat.block(12).mfs = 1;
M_.block_structure_stat.block(12).equation = [ 13];
M_.block_structure_stat.block(12).variable = [ 13];
M_.block_structure_stat.block(13).Simulation_Type = 3;
M_.block_structure_stat.block(13).endo_nbr = 1;
M_.block_structure_stat.block(13).mfs = 1;
M_.block_structure_stat.block(13).equation = [ 14];
M_.block_structure_stat.block(13).variable = [ 14];
M_.block_structure_stat.block(14).Simulation_Type = 1;
M_.block_structure_stat.block(14).endo_nbr = 1;
M_.block_structure_stat.block(14).mfs = 1;
M_.block_structure_stat.block(14).equation = [ 18];
M_.block_structure_stat.block(14).variable = [ 18];
M_.block_structure_stat.block(15).Simulation_Type = 3;
M_.block_structure_stat.block(15).endo_nbr = 1;
M_.block_structure_stat.block(15).mfs = 1;
M_.block_structure_stat.block(15).equation = [ 15];
M_.block_structure_stat.block(15).variable = [ 15];
M_.block_structure_stat.variable_reordered = [ 5 6 7 8 9 10 11 12 16 17 2 1 3 4 13 14 18 15];
M_.block_structure_stat.equation_reordered = [ 5 6 7 8 9 10 11 12 16 17 3 1 2 4 13 14 18 15];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 5;
 2 1;
 2 2;
 2 3;
 3 1;
 3 2;
 3 8;
 3 10;
 3 11;
 3 12;
 4 1;
 4 4;
 5 5;
 6 5;
 6 6;
 7 7;
 8 8;
 9 9;
 10 10;
 11 11;
 12 12;
 13 1;
 13 4;
 13 13;
 14 1;
 14 2;
 14 3;
 14 4;
 14 13;
 14 14;
 15 1;
 15 3;
 15 14;
 15 15;
 15 16;
 15 17;
 15 18;
 16 16;
 17 16;
 17 17;
 18 1;
 18 2;
 18 3;
 18 4;
 18 5;
 18 6;
 18 7;
 18 8;
 18 9;
 18 10;
 18 11;
 18 12;
 18 13;
 18 14;
 18 18;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(8).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(9).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(9).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(9).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(10).g1_sparse_rowval = int32([1 2 3 1 2 3 2 3 ]);
M_.block_structure_stat.block(10).g1_sparse_colval = int32([1 1 1 2 2 2 3 3 ]);
M_.block_structure_stat.block(10).g1_sparse_colptr = int32([1 4 7 9 ]);
M_.block_structure_stat.block(11).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(12).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(13).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(13).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(13).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(14).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(14).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(14).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(15).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(15).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(15).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 2 3 4 13 14 15 18 1 2 3 14 18 1 2 14 15 18 4 13 14 18 1 5 6 18 6 18 7 18 3 8 18 9 18 3 10 18 3 11 18 3 12 18 13 14 18 14 15 18 15 15 16 17 15 17 15 18 ]);
M_.static_g1_sparse_colval = int32([1 1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 5 5 5 5 6 6 7 7 8 8 8 9 9 10 10 10 11 11 11 12 12 12 13 13 13 14 14 14 15 16 16 16 17 17 18 18 ]);
M_.static_g1_sparse_colptr = int32([1 9 14 19 23 27 29 31 34 36 39 42 45 48 51 52 55 57 59 ]);
M_.params(1) = 0.1989;
delta = M_.params(1);
M_.params(2) = 0.6959;
lambda_q = M_.params(2);
M_.params(3) = 0.0648;
sigma_q = M_.params(3);
M_.params(4) = 0.9576;
lambda_i = M_.params(4);
M_.params(5) = 0.3001;
alpha_i = M_.params(5);
M_.params(6) = 0.0837;
beta_i = M_.params(6);
M_.params(7) = 0.2902;
lambda_pi = M_.params(7);
M_.params(8) = 0.0374;
kappa_pi = M_.params(8);
M_.params(9) = 0.8057;
lambda_q_us = M_.params(9);
M_.params(10) = 0.6529;
lambda_pi_us = M_.params(10);
M_.params(11) = 0.0131;
kappa_pi_us = M_.params(11);
M_.params(12) = 0.985;
lambda_ibar = M_.params(12);
M_.params(13) = 0.93;
lambda_pibar = M_.params(13);
M_.params(14) = 0.93;
lambda_pibar_us = M_.params(14);
M_.params(15) = 0.94;
rho_u_gap = M_.params(15);
M_.params(16) = (-0.33);
okun_coeff = M_.params(16);
M_.params(17) = 0.17;
alpha_pc = M_.params(17);
M_.params(18) = 0.10;
beta_pc_m = M_.params(18);
M_.params(19) = 0.03;
gamma_oil = M_.params(19);
M_.params(20) = 1.0491;
i_ss = M_.params(20);
M_.params(21) = 0.625;
pi_ss_au = M_.params(21);
M_.params(22) = 0.5;
pi_ss_us = M_.params(22);
M_.params(23) = 0.85;
rho_piQ = M_.params(23);
M_.params(24) = 0.7;
rho_pi_m = M_.params(24);
M_.params(25) = 0.42;
rho_pcom = M_.params(25);
M_.params(26) = 0.6;
rho_yh_aux = M_.params(26);
M_.params(27) = 0.4;
a_yh_y = M_.params(27);
M_.params(28) = (-0.2);
a_yh_u = M_.params(28);
M_.params(29) = 0.6;
rho_c_aux = M_.params(29);
M_.params(30) = 0.06;
a_c_y = M_.params(30);
M_.params(31) = (-0.04);
a_c_i = M_.params(31);
M_.params(32) = 0.005;
a_c_pi = M_.params(32);
M_.params(33) = (-0.03);
a_c_u = M_.params(33);
M_.params(34) = 0.39;
a_c_yh = M_.params(34);
M_.params(35) = 0.0736;
b0_c = M_.params(35);
M_.params(36) = 0.0375;
b1_c = M_.params(36);
M_.params(37) = (-0.3330);
b2_c = M_.params(37);
M_.params(38) = 0.0220;
b3_c = M_.params(38);
M_.params(39) = 0.95;
beta_pac = M_.params(39);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.527)^2;
M_.Sigma_e(2, 2) = (0.110)^2;
M_.Sigma_e(3, 3) = (0.590)^2;
M_.Sigma_e(4, 4) = (1.138)^2;
M_.Sigma_e(5, 5) = (0.319)^2;
M_.Sigma_e(6, 6) = (0.01)^2;
M_.Sigma_e(7, 7) = (0.01)^2;
M_.Sigma_e(8, 8) = (0.01)^2;
M_.Sigma_e(9, 9) = (0.05)^2;
M_.Sigma_e(10, 10) = (0.571)^2;
M_.Sigma_e(11, 11) = (0.5)^2;
M_.Sigma_e(12, 12) = (3.0)^2;
M_.Sigma_e(13, 13) = (0.01)^2;
M_.Sigma_e(14, 14) = (0.01)^2;
M_.Sigma_e(15, 15) = (1.81)^2;
pac.initialize('pac_c');
pac.update.expectation('pac_c');
pac.print('pac_c', 'eq_dln_c_pac');


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'aux_consumption_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
