function [ar, a0, constants] = varmatrices(model_name, params, reducedform)
% File automatically generated by the Dynare preprocessor

if nargin<3
    reducedform = false;
end

if strcmp(model_name, 'esat_consumption')
    ar = zeros(14, 14, 1);
    ar(1,1,1) = params(2);
    ar(1,3,1) = params(3);
    ar(1,2,1) = (-params(3));
    ar(1,5,1) = params(1);
    ar(2,1,1) = (1-params(4))*params(6);
    ar(2,3,1) = (1-params(4))*params(5);
    ar(2,2,1) = params(4);
    ar(3,1,1) = params(8);
    ar(3,3,1) = params(7);
    ar(3,8,1) = (-params(17))-params(18);
    ar(3,10,1) = params(17);
    ar(3,11,1) = params(18);
    ar(3,12,1) = params(19);
    ar(4,1,1) = params(16);
    ar(4,4,1) = params(15);
    ar(5,5,1) = params(9);
    ar(6,5,1) = params(11);
    ar(6,6,1) = params(10);
    ar(7,7,1) = params(12);
    ar(8,8,1) = params(13);
    ar(9,9,1) = params(14);
    ar(10,10,1) = params(23);
    ar(11,11,1) = params(24);
    ar(12,12,1) = params(25);
    ar(13,1,1) = params(27);
    ar(13,4,1) = params(28);
    ar(13,13,1) = params(26);
    ar(14,1,1) = params(30);
    ar(14,3,1) = params(32);
    ar(14,2,1) = params(31);
    ar(14,4,1) = params(33);
    ar(14,13,1) = params(34);
    ar(14,14,1) = params(29);
    if nargout>1
        a0 = eye(14);
        if reducedform
            for i=1:1
                ar(:,:,i) = a0\ar(:,:,i);
            end
            if nargout<3
                a0 = eye(14);
            end
        end
        if nargout>2
            constants = zeros(14,1);
            constants(7) = (1-params(12))*params(20);
            constants(8) = (1-params(13))*params(21);
            constants(9) = (1-params(14))*params(22);
            constants(10) = params(21)*(1-params(23));
            constants(11) = params(21)*(1-params(24));
        end
        if reducedform
            constants = a0\constants;
            a0 = eye(14);
        end
    end
    return
end

error('%s is not a valid var_model name', model_name)
