%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'test_var_pac_multi';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'eps_y'};
M_.exo_names_tex(1) = {'eps\_y'};
M_.exo_names_long(1) = {'eps_y'};
M_.exo_names(2) = {'eps_i'};
M_.exo_names_tex(2) = {'eps\_i'};
M_.exo_names_long(2) = {'eps_i'};
M_.exo_names(3) = {'eps_pi'};
M_.exo_names_tex(3) = {'eps\_pi'};
M_.exo_names_long(3) = {'eps_pi'};
M_.exo_names(4) = {'eps_pQ_aux'};
M_.exo_names_tex(4) = {'eps\_pQ\_aux'};
M_.exo_names_long(4) = {'eps_pQ_aux'};
M_.exo_names(5) = {'eps_n_aux'};
M_.exo_names_tex(5) = {'eps\_n\_aux'};
M_.exo_names_long(5) = {'eps_n_aux'};
M_.exo_names(6) = {'eps_pQ'};
M_.exo_names_tex(6) = {'eps\_pQ'};
M_.exo_names_long(6) = {'eps_pQ'};
M_.exo_names(7) = {'eps_n'};
M_.exo_names_tex(7) = {'eps\_n'};
M_.exo_names_long(7) = {'eps_n'};
M_.endo_names = cell(15,1);
M_.endo_names_tex = cell(15,1);
M_.endo_names_long = cell(15,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'y\_gap'};
M_.endo_names_long(1) = {'y_gap'};
M_.endo_names(2) = {'i_gap'};
M_.endo_names_tex(2) = {'i\_gap'};
M_.endo_names_long(2) = {'i_gap'};
M_.endo_names(3) = {'pi_gap'};
M_.endo_names_tex(3) = {'pi\_gap'};
M_.endo_names_long(3) = {'pi_gap'};
M_.endo_names(4) = {'piQ_hat'};
M_.endo_names_tex(4) = {'piQ\_hat'};
M_.endo_names_long(4) = {'piQ_hat'};
M_.endo_names(5) = {'n_hat'};
M_.endo_names_tex(5) = {'n\_hat'};
M_.endo_names_long(5) = {'n_hat'};
M_.endo_names(6) = {'piQ'};
M_.endo_names_tex(6) = {'piQ'};
M_.endo_names_long(6) = {'piQ'};
M_.endo_names(7) = {'pQ_level'};
M_.endo_names_tex(7) = {'pQ\_level'};
M_.endo_names_long(7) = {'pQ_level'};
M_.endo_names(8) = {'dln_n'};
M_.endo_names_tex(8) = {'dln\_n'};
M_.endo_names_long(8) = {'dln_n'};
M_.endo_names(9) = {'ln_n_level'};
M_.endo_names_tex(9) = {'ln\_n\_level'};
M_.endo_names_long(9) = {'ln_n_level'};
M_.endo_names(10) = {'AUX_DIFF_77'};
M_.endo_names_tex(10) = {'AUX\_DIFF\_77'};
M_.endo_names_long(10) = {'AUX_DIFF_77'};
M_.endo_names(11) = {'AUX_DIFF_LAG_78'};
M_.endo_names_tex(11) = {'AUX\_DIFF\_LAG\_78'};
M_.endo_names_long(11) = {'AUX_DIFF_LAG_78'};
M_.endo_names(12) = {'AUX_DIFF_82'};
M_.endo_names_tex(12) = {'AUX\_DIFF\_82'};
M_.endo_names_long(12) = {'AUX_DIFF_82'};
M_.endo_names(13) = {'AUX_DIFF_LAG_83'};
M_.endo_names_tex(13) = {'AUX\_DIFF\_LAG\_83'};
M_.endo_names_long(13) = {'AUX_DIFF_LAG_83'};
M_.endo_names(14) = {'pac_expectation_pac_n'};
M_.endo_names_tex(14) = {'pac\_expectation\_pac\_n'};
M_.endo_names_long(14) = {'pac_expectation_pac_n'};
M_.endo_names(15) = {'pac_expectation_pac_piQ'};
M_.endo_names_tex(15) = {'pac\_expectation\_pac\_piQ'};
M_.endo_names_long(15) = {'pac_expectation_pac_piQ'};
M_.endo_partitions = struct();
M_.param_names = cell(34,1);
M_.param_names_tex = cell(34,1);
M_.param_names_long = cell(34,1);
M_.param_names(1) = {'lambda_q'};
M_.param_names_tex(1) = {'lambda\_q'};
M_.param_names_long(1) = {'lambda_q'};
M_.param_names(2) = {'sigma_q'};
M_.param_names_tex(2) = {'sigma\_q'};
M_.param_names_long(2) = {'sigma_q'};
M_.param_names(3) = {'lambda_i'};
M_.param_names_tex(3) = {'lambda\_i'};
M_.param_names_long(3) = {'lambda_i'};
M_.param_names(4) = {'alpha_i'};
M_.param_names_tex(4) = {'alpha\_i'};
M_.param_names_long(4) = {'alpha_i'};
M_.param_names(5) = {'beta_i_par'};
M_.param_names_tex(5) = {'beta\_i\_par'};
M_.param_names_long(5) = {'beta_i_par'};
M_.param_names(6) = {'lambda_pi'};
M_.param_names_tex(6) = {'lambda\_pi'};
M_.param_names_long(6) = {'lambda_pi'};
M_.param_names(7) = {'kappa_pi'};
M_.param_names_tex(7) = {'kappa\_pi'};
M_.param_names_long(7) = {'kappa_pi'};
M_.param_names(8) = {'rho_pQ_hat'};
M_.param_names_tex(8) = {'rho\_pQ\_hat'};
M_.param_names_long(8) = {'rho_pQ_hat'};
M_.param_names(9) = {'a_pQ_y'};
M_.param_names_tex(9) = {'a\_pQ\_y'};
M_.param_names_long(9) = {'a_pQ_y'};
M_.param_names(10) = {'a_pQ_i'};
M_.param_names_tex(10) = {'a\_pQ\_i'};
M_.param_names_long(10) = {'a_pQ_i'};
M_.param_names(11) = {'a_pQ_pi'};
M_.param_names_tex(11) = {'a\_pQ\_pi'};
M_.param_names_long(11) = {'a_pQ_pi'};
M_.param_names(12) = {'rho_n_hat'};
M_.param_names_tex(12) = {'rho\_n\_hat'};
M_.param_names_long(12) = {'rho_n_hat'};
M_.param_names(13) = {'a_n_y'};
M_.param_names_tex(13) = {'a\_n\_y'};
M_.param_names_long(13) = {'a_n_y'};
M_.param_names(14) = {'a_n_i'};
M_.param_names_tex(14) = {'a\_n\_i'};
M_.param_names_long(14) = {'a_n_i'};
M_.param_names(15) = {'a_n_pi'};
M_.param_names_tex(15) = {'a\_n\_pi'};
M_.param_names_long(15) = {'a_n_pi'};
M_.param_names(16) = {'b0_pQ'};
M_.param_names_tex(16) = {'b0\_pQ'};
M_.param_names_long(16) = {'b0_pQ'};
M_.param_names(17) = {'b1_pQ'};
M_.param_names_tex(17) = {'b1\_pQ'};
M_.param_names_long(17) = {'b1_pQ'};
M_.param_names(18) = {'b2_pQ'};
M_.param_names_tex(18) = {'b2\_pQ'};
M_.param_names_long(18) = {'b2_pQ'};
M_.param_names(19) = {'b0_n'};
M_.param_names_tex(19) = {'b0\_n'};
M_.param_names_long(19) = {'b0_n'};
M_.param_names(20) = {'b1_n'};
M_.param_names_tex(20) = {'b1\_n'};
M_.param_names_long(20) = {'b1_n'};
M_.param_names(21) = {'b5_n'};
M_.param_names_tex(21) = {'b5\_n'};
M_.param_names_long(21) = {'b5_n'};
M_.param_names(22) = {'beta_pac'};
M_.param_names_tex(22) = {'beta\_pac'};
M_.param_names_long(22) = {'beta_pac'};
M_.param_names(23) = {'h_pac_n_constant'};
M_.param_names_tex(23) = {'h\_pac\_n\_constant'};
M_.param_names_long(23) = {'h_pac_n_constant'};
M_.param_names(24) = {'h_pac_n_var_y_gap_lag_1'};
M_.param_names_tex(24) = {'h\_pac\_n\_var\_y\_gap\_lag\_1'};
M_.param_names_long(24) = {'h_pac_n_var_y_gap_lag_1'};
M_.param_names(25) = {'h_pac_n_var_i_gap_lag_1'};
M_.param_names_tex(25) = {'h\_pac\_n\_var\_i\_gap\_lag\_1'};
M_.param_names_long(25) = {'h_pac_n_var_i_gap_lag_1'};
M_.param_names(26) = {'h_pac_n_var_pi_gap_lag_1'};
M_.param_names_tex(26) = {'h\_pac\_n\_var\_pi\_gap\_lag\_1'};
M_.param_names_long(26) = {'h_pac_n_var_pi_gap_lag_1'};
M_.param_names(27) = {'h_pac_n_var_piQ_hat_lag_1'};
M_.param_names_tex(27) = {'h\_pac\_n\_var\_piQ\_hat\_lag\_1'};
M_.param_names_long(27) = {'h_pac_n_var_piQ_hat_lag_1'};
M_.param_names(28) = {'h_pac_n_var_n_hat_lag_1'};
M_.param_names_tex(28) = {'h\_pac\_n\_var\_n\_hat\_lag\_1'};
M_.param_names_long(28) = {'h_pac_n_var_n_hat_lag_1'};
M_.param_names(29) = {'h_pac_piQ_constant'};
M_.param_names_tex(29) = {'h\_pac\_piQ\_constant'};
M_.param_names_long(29) = {'h_pac_piQ_constant'};
M_.param_names(30) = {'h_pac_piQ_var_y_gap_lag_1'};
M_.param_names_tex(30) = {'h\_pac\_piQ\_var\_y\_gap\_lag\_1'};
M_.param_names_long(30) = {'h_pac_piQ_var_y_gap_lag_1'};
M_.param_names(31) = {'h_pac_piQ_var_i_gap_lag_1'};
M_.param_names_tex(31) = {'h\_pac\_piQ\_var\_i\_gap\_lag\_1'};
M_.param_names_long(31) = {'h_pac_piQ_var_i_gap_lag_1'};
M_.param_names(32) = {'h_pac_piQ_var_pi_gap_lag_1'};
M_.param_names_tex(32) = {'h\_pac\_piQ\_var\_pi\_gap\_lag\_1'};
M_.param_names_long(32) = {'h_pac_piQ_var_pi_gap_lag_1'};
M_.param_names(33) = {'h_pac_piQ_var_piQ_hat_lag_1'};
M_.param_names_tex(33) = {'h\_pac\_piQ\_var\_piQ\_hat\_lag\_1'};
M_.param_names_long(33) = {'h_pac_piQ_var_piQ_hat_lag_1'};
M_.param_names(34) = {'h_pac_piQ_var_n_hat_lag_1'};
M_.param_names_tex(34) = {'h\_pac\_piQ\_var\_n\_hat\_lag\_1'};
M_.param_names_long(34) = {'h_pac_piQ_var_n_hat_lag_1'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 15;
M_.param_nbr = 34;
M_.orig_endo_nbr = 9;
M_.aux_vars(1).endo_index = 10;
M_.aux_vars(1).type = 8;
M_.aux_vars(1).orig_index = 7;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'diff(pQ_level)';
M_.aux_vars(2).endo_index = 11;
M_.aux_vars(2).type = 9;
M_.aux_vars(2).orig_index = 10;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'diff(pQ_level(-1))';
M_.aux_vars(3).endo_index = 12;
M_.aux_vars(3).type = 8;
M_.aux_vars(3).orig_index = 9;
M_.aux_vars(3).orig_lead_lag = 0;
M_.aux_vars(3).orig_expr = 'diff(ln_n_level)';
M_.aux_vars(4).endo_index = 13;
M_.aux_vars(4).type = 9;
M_.aux_vars(4).orig_index = 12;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(4).orig_expr = 'diff(ln_n_level(-1))';
M_.aux_vars(5).endo_index = 14;
M_.aux_vars(5).type = 12;
M_.aux_vars(5).orig_expr = 'h_pac_n_constant+y_gap(-1)*h_pac_n_var_y_gap_lag_1+i_gap(-1)*h_pac_n_var_i_gap_lag_1+pi_gap(-1)*h_pac_n_var_pi_gap_lag_1+piQ_hat(-1)*h_pac_n_var_piQ_hat_lag_1+n_hat(-1)*h_pac_n_var_n_hat_lag_1';
M_.aux_vars(6).endo_index = 15;
M_.aux_vars(6).type = 12;
M_.aux_vars(6).orig_expr = 'h_pac_piQ_constant+y_gap(-1)*h_pac_piQ_var_y_gap_lag_1+i_gap(-1)*h_pac_piQ_var_i_gap_lag_1+pi_gap(-1)*h_pac_piQ_var_pi_gap_lag_1+piQ_hat(-1)*h_pac_piQ_var_piQ_hat_lag_1+n_hat(-1)*h_pac_piQ_var_n_hat_lag_1';
M_.var.esat_full.model_name = 'esat_full';
M_.var.esat_full.structural = false;
M_.var.esat_full.eqtags = {'var_y'; 'var_i'; 'var_pi'; 'var_pQ'; 'var_n'; };
M_.var.esat_full.eqn = [1 2 3 4 5 ];
M_.var.esat_full.lhs = [1 2 3 4 5 ];
M_.var.esat_full.max_lag = [1 1 1 1 1 ];
M_.var.esat_full.diff = [false false false false false ];
M_.var.esat_full.nonstationary = M_.var.esat_full.diff;
M_.var.esat_full.orig_diff_var = [-1 -1 -1 -1 -1 ];
M_.var.esat_full.rhs.vars_at_eq{1}.var = [1 2 3 ];
M_.var.esat_full.rhs.vars_at_eq{1}.lag = [-1 -1 -1 ];
M_.var.esat_full.rhs.vars_at_eq{2}.var = [1 2 3 ];
M_.var.esat_full.rhs.vars_at_eq{2}.lag = [-1 -1 -1 ];
M_.var.esat_full.rhs.vars_at_eq{3}.var = [1 3 ];
M_.var.esat_full.rhs.vars_at_eq{3}.lag = [-1 -1 ];
M_.var.esat_full.rhs.vars_at_eq{4}.var = [1 2 3 4 ];
M_.var.esat_full.rhs.vars_at_eq{4}.lag = [-1 -1 -1 -1 ];
M_.var.esat_full.rhs.vars_at_eq{5}.var = [1 2 3 5 ];
M_.var.esat_full.rhs.vars_at_eq{5}.lag = [-1 -1 -1 -1 ];
M_.pac.pac_n.auxiliary_model_name = 'esat_full';
M_.pac.pac_n.discount_index = 22;
M_.pac.pac_piQ.auxiliary_model_name = 'esat_full';
M_.pac.pac_piQ.discount_index = 22;
M_.pac.pac_n.h_param_indices = [23 24 25 26 27 28 ];
M_.pac.pac_piQ.h_param_indices = [29 30 31 32 33 34 ];
M_.pac.pac_n.aux_id = 14;
M_.pac.pac_piQ.aux_id = 15;
M_.pac.pac_n.eq_name = 'eq_dln_n_pac';
M_.pac.pac_piQ.eq_name = 'eq_piQ_pac';
M_.pac.pac_n.auxiliary_model_type = 'var';
M_.pac.pac_piQ.auxiliary_model_type = 'var';
M_.pac.pac_n.kind = '';
M_.pac.pac_piQ.kind = '';
M_.pac.pac_n.lhs_var = 12;
M_.pac.pac_n.ec.params = 19;
M_.pac.pac_n.ec.vars = [5 9 ];
M_.pac.pac_n.ec.istarget = [true false ];
M_.pac.pac_n.ec.scale = [1 -1 ];
M_.pac.pac_n.ec.isendo = [true true ];
M_.pac.pac_n.ar.params = [20 ];
M_.pac.pac_n.ar.vars = [13 ];
M_.pac.pac_n.ar.lags = [0 ];
M_.pac.pac_n.max_lag = 1;
M_.pac.pac_n.additive.params = [NaN 21 ];
M_.pac.pac_n.additive.vars = [7 1 ];
M_.pac.pac_n.additive.isendo = [false true ];
M_.pac.pac_n.additive.lags = [0 0 ];
M_.pac.pac_n.additive.scaling_factor = [1 1 ];
M_.pac.pac_piQ.lhs_var = 10;
M_.pac.pac_piQ.ec.params = 16;
M_.pac.pac_piQ.ec.vars = [4 7 ];
M_.pac.pac_piQ.ec.istarget = [true false ];
M_.pac.pac_piQ.ec.scale = [1 -1 ];
M_.pac.pac_piQ.ec.isendo = [true true ];
M_.pac.pac_piQ.ar.params = [17 ];
M_.pac.pac_piQ.ar.vars = [11 ];
M_.pac.pac_piQ.ar.lags = [0 ];
M_.pac.pac_piQ.max_lag = 1;
M_.pac.pac_piQ.additive.params = [NaN 18 ];
M_.pac.pac_piQ.additive.vars = [6 1 ];
M_.pac.pac_piQ.additive.isendo = [false true ];
M_.pac.pac_piQ.additive.lags = [0 0 ];
M_.pac.pac_piQ.additive.scaling_factor = [1 1 ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.eq_nbr = 15;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 0;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 0;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 1 10;
 2 11;
 3 12;
 4 13;
 5 14;
 0 15;
 6 16;
 0 17;
 7 18;
 8 19;
 0 20;
 9 21;
 0 22;
 0 23;
 0 24;]';
M_.nstatic = 6;
M_.nfwrd   = 0;
M_.npred   = 9;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 9;
M_.ndynamic   = 9;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'var_y' ;
  2 , 'name' , 'var_i' ;
  3 , 'name' , 'var_pi' ;
  4 , 'name' , 'var_pQ' ;
  5 , 'name' , 'var_n' ;
  6 , 'name' , 'eq_pQ_level' ;
  7 , 'name' , 'eq_ln_n_level' ;
  8 , 'name' , 'eq_piQ_pac' ;
  9 , 'name' , 'eq_dln_n_pac' ;
};
M_.mapping.y_gap.eqidx = [1 2 3 4 5 8 9 14 15 ];
M_.mapping.i_gap.eqidx = [1 2 4 5 14 15 ];
M_.mapping.pi_gap.eqidx = [1 2 3 4 5 14 15 ];
M_.mapping.piQ_hat.eqidx = [4 8 14 15 ];
M_.mapping.n_hat.eqidx = [5 9 14 15 ];
M_.mapping.piQ.eqidx = [6 ];
M_.mapping.pQ_level.eqidx = [6 8 10 11 ];
M_.mapping.dln_n.eqidx = [7 ];
M_.mapping.ln_n_level.eqidx = [7 9 12 13 ];
M_.mapping.eps_y.eqidx = [1 ];
M_.mapping.eps_i.eqidx = [2 ];
M_.mapping.eps_pi.eqidx = [3 ];
M_.mapping.eps_pQ_aux.eqidx = [4 ];
M_.mapping.eps_n_aux.eqidx = [5 ];
M_.mapping.eps_pQ.eqidx = [8 ];
M_.mapping.eps_n.eqidx = [9 ];
M_.mapping.pac_expectation_pac_n.eqidx = [9 14 ];
M_.mapping.pac_expectation_pac_piQ.eqidx = [8 15 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = true;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 15;
M_.block_structure.block(1).mfs = 15;
M_.block_structure.block(1).equation = [ 1 2 3 4 5 11 13 14 15 8 9 12 7 10 6];
M_.block_structure.block(1).variable = [ 1 2 3 4 5 11 13 14 15 10 12 9 8 7 6];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 25;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 10 11 12 14 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 1 2 3 4 5 11 13 14 15 10 12 9 8 7 6];
M_.block_structure.equation_reordered = [ 1 2 3 4 5 11 13 14 15 8 9 12 7 10 6];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 1;
 1 2;
 1 3;
 2 1;
 2 2;
 2 3;
 3 1;
 3 3;
 4 1;
 4 2;
 4 3;
 4 4;
 5 1;
 5 2;
 5 3;
 5 5;
 6 7;
 7 9;
 8 4;
 8 7;
 9 5;
 9 9;
 10 7;
 11 10;
 12 9;
 13 12;
 14 1;
 14 2;
 14 3;
 14 4;
 14 5;
 15 1;
 15 2;
 15 3;
 15 4;
 15 5;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 2 2;
 3 3;
 4 4;
 5 5;
 6 6;
 6 7;
 7 8;
 7 9;
 8 1;
 8 10;
 8 11;
 8 15;
 9 1;
 9 12;
 9 13;
 9 14;
 10 7;
 10 10;
 11 11;
 12 9;
 12 12;
 13 13;
 14 14;
 15 15;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [1 2 3 4 5 10 12 9 7 ];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(15, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(34, 1);
M_.endo_trends = struct('deflator', cell(15, 1), 'log_deflator', cell(15, 1), 'growth_factor', cell(15, 1), 'log_growth_factor', cell(15, 1));
M_.NNZDerivatives = [68; -1; -1; ];
M_.dynamic_g1_sparse_rowval = int32([1 2 3 4 5 14 15 1 2 4 5 14 15 1 2 3 4 5 14 15 4 8 14 15 5 9 14 15 6 8 10 7 9 12 11 13 1 8 9 2 3 4 5 6 6 10 7 7 12 8 10 8 11 9 12 9 13 9 14 8 15 1 2 3 4 5 8 9 ]);
M_.dynamic_g1_sparse_colval = int32([1 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 4 4 4 4 5 5 5 5 7 7 7 9 9 9 10 12 16 16 16 17 18 19 20 21 22 22 23 24 24 25 25 26 26 27 27 28 28 29 29 30 30 46 47 48 49 50 51 52 ]);
M_.dynamic_g1_sparse_colptr = int32([1 8 14 21 25 29 29 32 32 35 36 36 37 37 37 37 40 41 42 43 44 45 47 48 50 52 54 56 58 60 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 63 64 65 66 67 68 69 ]);
M_.lhs = {
'y_gap'; 
'i_gap'; 
'pi_gap'; 
'piQ_hat'; 
'n_hat'; 
'pQ_level'; 
'ln_n_level'; 
'AUX_DIFF_77'; 
'AUX_DIFF_82'; 
'AUX_DIFF_77'; 
'AUX_DIFF_LAG_78'; 
'AUX_DIFF_82'; 
'AUX_DIFF_LAG_83'; 
'pac_expectation_pac_n'; 
'pac_expectation_pac_piQ'; 
};
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 4;
M_.block_structure_stat.block(1).mfs = 4;
M_.block_structure_stat.block(1).equation = [ 10 11 12 13];
M_.block_structure_stat.block(1).variable = [ 10 11 12 13];
M_.block_structure_stat.block(2).Simulation_Type = 6;
M_.block_structure_stat.block(2).endo_nbr = 3;
M_.block_structure_stat.block(2).mfs = 3;
M_.block_structure_stat.block(2).equation = [ 3 2 1];
M_.block_structure_stat.block(2).variable = [ 3 2 1];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 5];
M_.block_structure_stat.block(3).variable = [ 5];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 4];
M_.block_structure_stat.block(4).variable = [ 4];
M_.block_structure_stat.block(5).Simulation_Type = 1;
M_.block_structure_stat.block(5).endo_nbr = 2;
M_.block_structure_stat.block(5).mfs = 2;
M_.block_structure_stat.block(5).equation = [ 14 15];
M_.block_structure_stat.block(5).variable = [ 14 15];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 9];
M_.block_structure_stat.block(6).variable = [ 9];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 8];
M_.block_structure_stat.block(7).variable = [ 7];
M_.block_structure_stat.block(8).Simulation_Type = 3;
M_.block_structure_stat.block(8).endo_nbr = 1;
M_.block_structure_stat.block(8).mfs = 1;
M_.block_structure_stat.block(8).equation = [ 7];
M_.block_structure_stat.block(8).variable = [ 8];
M_.block_structure_stat.block(9).Simulation_Type = 3;
M_.block_structure_stat.block(9).endo_nbr = 1;
M_.block_structure_stat.block(9).mfs = 1;
M_.block_structure_stat.block(9).equation = [ 6];
M_.block_structure_stat.block(9).variable = [ 6];
M_.block_structure_stat.variable_reordered = [ 10 11 12 13 3 2 1 5 4 14 15 9 7 8 6];
M_.block_structure_stat.equation_reordered = [ 10 11 12 13 3 2 1 5 4 14 15 9 8 7 6];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 3;
 2 1;
 2 2;
 2 3;
 3 1;
 3 3;
 4 1;
 4 2;
 4 3;
 4 4;
 5 1;
 5 2;
 5 3;
 5 5;
 6 6;
 7 8;
 8 1;
 8 4;
 8 7;
 8 10;
 8 11;
 8 15;
 9 1;
 9 5;
 9 9;
 9 12;
 9 13;
 9 14;
 10 10;
 11 10;
 11 11;
 12 12;
 13 12;
 13 13;
 14 1;
 14 2;
 14 3;
 14 4;
 14 5;
 14 14;
 15 1;
 15 2;
 15 3;
 15 4;
 15 5;
 15 15;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 2 3 2 3 1 2 3 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 1 1 2 2 3 3 3 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 4 6 9 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(8).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(9).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(9).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(9).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 2 3 4 5 8 9 14 15 1 2 4 5 14 15 1 2 3 4 5 14 15 4 8 14 15 5 9 14 15 6 8 7 9 8 10 11 8 11 9 12 13 9 13 9 14 8 15 ]);
M_.static_g1_sparse_colval = int32([1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 4 4 4 4 5 5 5 5 6 7 8 9 10 10 10 11 11 12 12 12 13 13 14 14 15 15 ]);
M_.static_g1_sparse_colptr = int32([1 10 16 23 27 31 32 33 34 35 38 40 43 45 47 49 ]);
M_.params(1) = 0.45;
lambda_q = M_.params(1);
M_.params(2) = 0.17;
sigma_q = M_.params(2);
M_.params(3) = 0.83;
lambda_i = M_.params(3);
M_.params(4) = 0.28;
alpha_i = M_.params(4);
M_.params(5) = 0.14;
beta_i_par = M_.params(5);
M_.params(6) = 0.26;
lambda_pi = M_.params(6);
M_.params(7) = 0.06;
kappa_pi = M_.params(7);
M_.params(8) = 0.70;
rho_pQ_hat = M_.params(8);
M_.params(9) = 0.08;
a_pQ_y = M_.params(9);
M_.params(10) = (-0.03);
a_pQ_i = M_.params(10);
M_.params(11) = 0.02;
a_pQ_pi = M_.params(11);
M_.params(12) = 0.67;
rho_n_hat = M_.params(12);
M_.params(13) = 0.12;
a_n_y = M_.params(13);
M_.params(14) = (-0.03);
a_n_i = M_.params(14);
M_.params(15) = 0.05;
a_n_pi = M_.params(15);
M_.params(16) = 0.06;
b0_pQ = M_.params(16);
M_.params(17) = 0.50;
b1_pQ = M_.params(17);
M_.params(18) = 0.09;
b2_pQ = M_.params(18);
M_.params(19) = 0.04;
b0_n = M_.params(19);
M_.params(20) = 0.30;
b1_n = M_.params(20);
M_.params(21) = 0.12;
b5_n = M_.params(21);
M_.params(22) = 0.98;
beta_pac = M_.params(22);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.34)^2;
M_.Sigma_e(2, 2) = (0.10)^2;
M_.Sigma_e(3, 3) = (0.26)^2;
M_.Sigma_e(4, 4) = (0.50)^2;
M_.Sigma_e(5, 5) = (0.50)^2;
M_.Sigma_e(6, 6) = (0.50)^2;
M_.Sigma_e(7, 7) = (0.50)^2;
pac.initialize('pac_piQ');
pac.update.expectation('pac_piQ');
pac.initialize('pac_n');
pac.update.expectation('pac_n');
options_.irf = 40;
options_.nograph = true;
options_.order = 1;
var_list_ = {'y_gap';'i_gap';'pi_gap';'piQ';'dln_n';'piQ_hat';'n_hat'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'test_var_pac_multi_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
