function [ar, a0, constants] = varmatrices(model_name, params, reducedform)
% File automatically generated by the Dynare preprocessor

if nargin<3
    reducedform = false;
end

if strcmp(model_name, 'esat_full')
    ar = zeros(5, 5, 1);
    ar(1,1,1) = params(1);
    ar(1,2,1) = (-params(2));
    ar(1,3,1) = params(2);
    ar(2,1,1) = (1-params(3))*params(5);
    ar(2,2,1) = params(3);
    ar(2,3,1) = (1-params(3))*params(4);
    ar(3,1,1) = params(7);
    ar(3,3,1) = params(6);
    ar(4,1,1) = params(9);
    ar(4,2,1) = params(10);
    ar(4,3,1) = params(11);
    ar(4,4,1) = params(8);
    ar(5,1,1) = params(13);
    ar(5,2,1) = params(14);
    ar(5,3,1) = params(15);
    ar(5,5,1) = params(12);
    if nargout>1
        a0 = eye(5);
        if reducedform
            for i=1:1
                ar(:,:,i) = a0\ar(:,:,i);
            end
            if nargout<3
                a0 = eye(5);
            end
        end
        if nargout>2
            constants = zeros(5,1);
        end
        if reducedform
            constants = a0\constants;
            a0 = eye(5);
        end
    end
    return
end

error('%s is not a valid var_model name', model_name)
